import type { MockExamQuestionType } from "@/lib/mock-exams/types";

import type { BridgeDefinition } from "./question-system-bridge";

export const MOCK_EXAM_QUESTION_BRIDGE = {
  multiple_choice: {
    taskContext: "mock_exam_section",
    interactionType: "single_choice",
    status: "covered",
    notes: "Radio-style objective question.",
  },
  multiple_response: {
    taskContext: "mock_exam_section",
    interactionType: "multi_select",
    status: "covered",
    notes: "Checkbox-style objective question.",
  },
  short_answer: {
    taskContext: "mock_exam_section",
    interactionType: "short_answer_en",
    status: "covered",
    notes: "Best used for English comprehension answers.",
  },
  gap_fill: {
    taskContext: "mock_exam_section",
    interactionType: "word_bank_gap_fill",
    secondaryInteractionTypes: ["dropdown_gap_fill"],
    status: "partial",
    notes: "Use selectable words by default when gaps contain Russian.",
  },
  matching: {
    taskContext: "mock_exam_section",
    interactionType: "matching",
    secondaryInteractionTypes: ["speaker_identification"],
    status: "covered",
    notes: "Can be shared with speaker-identification tasks.",
  },
  sequencing: {
    taskContext: "mock_exam_section",
    interactionType: "ordering",
    status: "needs_new_interaction",
    notes: "Should use tap or drag ordering rather than typed index lists.",
  },
  opinion_recognition: {
    taskContext: "mock_exam_section",
    interactionType: "opinion_recognition",
    status: "covered",
    notes: "Statement-level polarity or attitude selection.",
  },
  true_false_not_mentioned: {
    taskContext: "mock_exam_section",
    interactionType: "true_false_not_mentioned",
    status: "covered",
    notes: "Standard GCSE reading/listening classification.",
  },
  translation_into_english: {
    taskContext: "mock_exam_section",
    interactionType: "translation_ru_en",
    status: "partial",
    notes: "Typed English is acceptable, but marking needs rubric/mark-scheme metadata.",
  },
  translation_into_russian: {
    taskContext: "mock_exam_section",
    interactionType: "translation_en_ru_tiles",
    secondaryInteractionTypes: ["writing_upload"],
    status: "needs_new_interaction",
    notes:
      "Avoid default Cyrillic typing; use tiles for controlled tasks or upload for open writing.",
  },
  writing_task: {
    taskContext: "writing_task",
    interactionType: "writing_upload",
    secondaryInteractionTypes: ["writing_draft_optional"],
    status: "needs_new_interaction",
    notes: "Needs upload/draft workflow and rubric metadata.",
  },
  simple_sentences: {
    taskContext: "writing_task",
    interactionType: "sentence_builder",
    secondaryInteractionTypes: ["writing_upload", "writing_draft_optional"],
    status: "partial",
    notes: "Can begin as scaffolded sentence building before open writing.",
  },
  short_paragraph: {
    taskContext: "writing_task",
    interactionType: "writing_upload",
    secondaryInteractionTypes: ["writing_draft_optional"],
    status: "needs_new_interaction",
    notes: "Needs upload/draft workflow and rubric metadata.",
  },
  extended_writing: {
    taskContext: "writing_task",
    interactionType: "writing_upload",
    secondaryInteractionTypes: ["writing_draft_optional"],
    status: "needs_new_interaction",
    notes: "Needs upload/draft workflow and rubric metadata.",
  },
  role_play: {
    taskContext: "speaking_task",
    interactionType: "role_play_response",
    secondaryInteractionTypes: ["speaking_prep_notes", "speaking_recording"],
    status: "needs_new_interaction",
    notes: "Needs prep, recording, and teacher/AI-assisted marking metadata.",
  },
  photo_card: {
    taskContext: "speaking_task",
    interactionType: "photo_card_response",
    secondaryInteractionTypes: ["speaking_prep_notes", "speaking_recording"],
    status: "needs_new_interaction",
    notes: "Needs image prompt, prep, recording, and marking metadata.",
  },
  conversation: {
    taskContext: "speaking_task",
    interactionType: "conversation_response",
    secondaryInteractionTypes: ["speaking_recording"],
    status: "needs_new_interaction",
    notes: "Needs recording workflow and speaking criteria metadata.",
  },
  sentence_builder: {
    taskContext: "mock_exam_section",
    interactionType: "sentence_builder",
    secondaryInteractionTypes: ["translation_en_ru_tiles"],
    status: "partial",
    notes: "Should share the same tile builder as question sets.",
  },
  note_completion: {
    taskContext: "mock_exam_section",
    interactionType: "note_completion_en",
    secondaryInteractionTypes: ["word_bank_gap_fill"],
    status: "partial",
    notes: "English notes can be typed; Russian notes should use choices.",
  },
  listening_comprehension: {
    taskContext: "listening_task",
    interactionType: "speaker_identification",
    secondaryInteractionTypes: [
      "single_choice",
      "matching",
      "true_false_not_mentioned",
      "opinion_recognition",
      "short_answer_en",
    ],
    status: "partial",
    notes: "Parent audio stimulus should hold child objective interactions.",
  },
  reading_comprehension: {
    taskContext: "reading_task",
    interactionType: "short_answer_en",
    secondaryInteractionTypes: [
      "single_choice",
      "matching",
      "true_false_not_mentioned",
      "opinion_recognition",
      "word_bank_gap_fill",
    ],
    status: "partial",
    notes: "Parent text stimulus should hold child objective interactions.",
  },
  other: {
    taskContext: "mock_exam_section",
    interactionType: "manual_marked_response",
    status: "migration_only",
    notes: "Migration-only escape hatch.",
  },
} as const satisfies Record<MockExamQuestionType, BridgeDefinition>;
