import {
  AudioLines,
  BookOpen,
  BookText,
  CheckCircle2,
  ChevronLeft,
  ChevronRight,
  CircleHelp,
  ClipboardList,
  Clock3,
  Eye,
  FileText,
  Filter,
  GraduationCap,
  Headphones,
  House,
  Image as ImageIcon,
  Languages,
  LayoutGrid,
  Lock,
  PenSquare,
  Search,
  Settings,
  SquarePen,
  Trash2,
  Unlock,
  User,
  Users,
  Volume2,
  WandSparkles,
} from "lucide-react";

export const appIcons = {
  home: House,
  dashboard: LayoutGrid,
  courses: GraduationCap,
  lessons: BookOpen,
  lessonContent: BookText,
  assignments: ClipboardList,
  translation: Languages,
  listening: Headphones,
  audio: AudioLines,
  vocabulary: Volume2,
  image: ImageIcon,
  file: FileText,
  completed: CheckCircle2,
  pending: Clock3,
  locked: Lock,
  unlocked: Unlock,
  help: CircleHelp,
  search: Search,
  filter: Filter,
  preview: Eye,
  edit: SquarePen,
  write: PenSquare,
  delete: Trash2,
  settings: Settings,
  user: User,
  users: Users,
  back: ChevronLeft,
  next: ChevronRight,
  uiLab: WandSparkles,
} as const;
