import {
  AlertCircle,
  AlertTriangle,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  AudioLines,
  Blocks,
  BookOpen,
  BookText,
  Brain,
  Check,
  CheckCircle2,
  CheckSquare,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CircleHelp,
  ClipboardList,
  Clock,
  Clock3,
  Component,
  Eye,
  EyeOff,
  File,
  FileText,
  Filter,
  Folder,
  FolderOpen,
  GraduationCap,
  Headphones,
  House,
  Image as ImageIcon,
  Info,
  Languages,
  LayoutGrid,
  Layers,
  Lightbulb,
  List,
  Lock,
  Menu,
  Mic,
  Moon,
  Palette,
  PenSquare,
  Pencil,
  Plus,
  RefreshCw,
  Save,
  School,
  Search,
  Settings,
  SquarePen,
  Sun,
  Trash2,
  Type,
  Unlock,
  User,
  UserCheck,
  UserX,
  Users,
  Volume2,
  WandSparkles,
  X,
} from "lucide-react";

export const appIcons = {
  home: House,
  dashboard: LayoutGrid,
  courses: BookOpen,
  lessons: BookOpen,
  lesson: FileText,
  lessonContent: BookText,
  assignments: ClipboardList,
  translation: Languages,
  listening: Headphones,
  audio: AudioLines,
  vocabulary: Volume2,
  image: ImageIcon,
  file: FileText,
  sun: Sun,
  moon: Moon,
  completed: CheckCircle2,
  pending: Clock3,
  locked: Lock,
  unlocked: Unlock,
  help: CircleHelp,
  search: Search,
  filter: Filter,
  preview: Eye,
  hidden: EyeOff,
  edit: SquarePen,
  write: PenSquare,
  create: Plus,
  delete: Trash2,
  settings: Settings,
  user: User,
  users: Users,
  back: ChevronLeft,
  next: ChevronRight,
  up: ChevronUp,
  down: ChevronDown,
  uiLab: WandSparkles,

  chevronRight: ChevronRight,
  chevronDown: ChevronDown,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  arrowUp: ArrowUp,
  arrowDown: ArrowDown,

  save: Save,
  confirm: Check,
  cancel: X,
  refresh: RefreshCw,

  modules: Layers,
  folder: Folder,
  folderOpen: FolderOpen,
  list: List,
  blocks: Blocks,
  menu: Menu,

  learning: GraduationCap,
  school: School,
  brain: Brain,
  idea: Lightbulb,
  language: Languages,

  userCheck: UserCheck,
  userX: UserX,

  warning: AlertTriangle,
  info: Info,
  alert: AlertCircle,

  component: Component,
  palette: Palette,

  speaking: Mic,

  question: CircleHelp,
  exercise: CheckSquare,
  text: Type,
  pencil: Pencil,
} as const;

export const curatedLucideIconNames = new Set<string>([
  "House",
  "LayoutGrid",
  "BookOpen",
  "FileText",
  "BookText",
  "ClipboardList",
  "Languages",
  "Headphones",
  "AudioLines",
  "Volume2",
  "Image",
  "CheckCircle2",
  "Clock3",
  "Lock",
  "Unlock",
  "CircleHelp",
  "Search",
  "Filter",
  "Eye",
  "EyeOff",
  "SquarePen",
  "PenSquare",
  "Plus",
  "Trash2",
  "Settings",
  "User",
  "Users",
  "ChevronLeft",
  "ChevronRight",
  "ChevronUp",
  "ChevronDown",
  "WandSparkles",
  "ArrowLeft",
  "ArrowRight",
  "ArrowUp",
  "ArrowDown",
  "Save",
  "Check",
  "X",
  "RefreshCw",
  "Layers",
  "Folder",
  "FolderOpen",
  "List",
  "Blocks",
  "Menu",
  "GraduationCap",
  "School",
  "Brain",
  "Lightbulb",
  "UserCheck",
  "UserX",
  "AlertTriangle",
  "Info",
  "AlertCircle",
  "Component",
  "Palette",
  "Mic",
  "CheckSquare",
  "Type",
  "Pencil",
  "Sun",
  "Moon",
]);

export type AppIconKey = keyof typeof appIcons;
