export const GRAMMAR_TAGS = [
  { key: "nouns", label: "Nouns", tier: "foundation", category: "noun", order: 1 },
  {
    key: "adjectives",
    label: "Adjectives",
    tier: "foundation",
    category: "adjective",
    order: 2,
  },
  { key: "adverbs", label: "Adverbs", tier: "foundation", category: "adverb", order: 3 },
  {
    key: "pronouns",
    label: "Pronouns",
    tier: "foundation",
    category: "pronoun",
    order: 4,
  },
  {
    key: "possessives",
    label: "Possessives",
    tier: "foundation",
    category: "pronoun",
    order: 5,
  },

  {
    key: "present_tense",
    label: "Present tense",
    tier: "foundation",
    category: "verb",
    order: 6,
  },
  {
    key: "past_tense",
    label: "Past tense",
    tier: "foundation",
    category: "verb",
    order: 7,
  },
  {
    key: "future_tense",
    label: "Future tense",
    tier: "foundation",
    category: "verb",
    order: 8,
  },
  {
    key: "reflexive_verbs",
    label: "Reflexive verbs",
    tier: "foundation",
    category: "verb",
    order: 9,
  },
  {
    key: "imperatives",
    label: "Imperatives",
    tier: "foundation",
    category: "verb",
    order: 10,
  },
  {
    key: "verbs_of_motion",
    label: "Verbs of motion",
    tier: "foundation",
    category: "verb",
    order: 11,
  },

  {
    key: "impersonal_constructions",
    label: "Impersonal constructions",
    tier: "foundation",
    category: "construction",
    order: 12,
  },
  {
    key: "numbers_and_quantity",
    label: "Numbers and quantity",
    tier: "foundation",
    category: "number",
    order: 13,
  },
  {
    key: "times_and_dates",
    label: "Times and dates",
    tier: "foundation",
    category: "time",
    order: 14,
  },
  {
    key: "negation",
    label: "Negation",
    tier: "foundation",
    category: "construction",
    order: 15,
  },
  {
    key: "prepositions",
    label: "Prepositions",
    tier: "foundation",
    category: "preposition",
    order: 16,
  },
  {
    key: "conjunctions",
    label: "Conjunctions",
    tier: "foundation",
    category: "conjunction",
    order: 17,
  },

  {
    key: "comparatives",
    label: "Comparatives",
    tier: "higher",
    category: "adjective",
    order: 18,
  },
  {
    key: "superlatives",
    label: "Superlatives",
    tier: "higher",
    category: "adjective",
    order: 19,
  },
  {
    key: "short_form_adjectives",
    label: "Short-form adjectives",
    tier: "higher",
    category: "adjective",
    order: 20,
  },
  {
    key: "perfective_future",
    label: "Perfective future",
    tier: "higher",
    category: "verb",
    order: 21,
  },
  {
    key: "complex_pronoun_usage",
    label: "Complex pronoun usage",
    tier: "higher",
    category: "pronoun",
    order: 22,
  },
  { key: "svoy", label: "Свой", tier: "higher", category: "pronoun", order: 23 },
  {
    key: "advanced_negation",
    label: "Advanced negation",
    tier: "higher",
    category: "construction",
    order: 24,
  },
] as const;

export type GrammarTagKey = (typeof GRAMMAR_TAGS)[number]["key"];
