import type {
  QuestionInteractionType,
  QuestionTaskContext,
} from "./question-taxonomy-types";

export const QUESTION_TASK_CONTEXTS = [
  {
    key: "standalone_practice",
    label: "Standalone practice",
    description: "A single reusable drill or practice question.",
    order: 1,
  },
  {
    key: "question_set",
    label: "Question set",
    description: "A reusable sequence of practice questions.",
    order: 2,
  },
  {
    key: "lesson_practice",
    label: "Lesson practice",
    description: "Practice embedded inside a lesson section.",
    order: 3,
  },
  {
    key: "reading_task",
    label: "Reading task",
    description: "A reading stimulus with one or more linked questions.",
    order: 4,
  },
  {
    key: "listening_task",
    label: "Listening task",
    description: "An audio stimulus with one or more linked questions.",
    order: 5,
  },
  {
    key: "writing_task",
    label: "Writing task",
    description: "A writing prompt, scaffold, draft, or upload task.",
    order: 6,
  },
  {
    key: "speaking_task",
    label: "Speaking task",
    description: "Role play, photo card, conversation, recording, or prep work.",
    order: 7,
  },
  {
    key: "mock_exam_section",
    label: "Mock exam section",
    description: "A section within a mock exam attempt.",
    order: 8,
  },
  {
    key: "assignment_task",
    label: "Assignment task",
    description: "A teacher-assigned task or question.",
    order: 9,
  },
] as const satisfies readonly QuestionTaskContext[];

export const QUESTION_INTERACTION_TYPES = [
  {
    key: "single_choice",
    label: "Single choice",
    description: "Student selects one correct option.",
    defaultInputMode: "select",
    responseLanguage: "none",
    defaultMarkingMode: "auto_exact",
    requiresRussianTyping: false,
    isExamAligned: true,
    order: 1,
  },
  {
    key: "multi_select",
    label: "Multi-select",
    description: "Student selects multiple correct options.",
    defaultInputMode: "multi_select",
    responseLanguage: "none",
    defaultMarkingMode: "auto_exact",
    requiresRussianTyping: false,
    isExamAligned: true,
    order: 2,
  },
  {
    key: "true_false_not_mentioned",
    label: "True / false / not mentioned",
    description: "Student classifies statements as true, false, or not mentioned.",
    defaultInputMode: "select",
    responseLanguage: "none",
    defaultMarkingMode: "auto_structured",
    requiresRussianTyping: false,
    isExamAligned: true,
    order: 3,
  },
  {
    key: "matching",
    label: "Matching",
    description: "Student matches prompts to options.",
    defaultInputMode: "select",
    responseLanguage: "none",
    defaultMarkingMode: "auto_structured",
    requiresRussianTyping: false,
    isExamAligned: true,
    order: 4,
  },
  {
    key: "categorisation",
    label: "Categorisation",
    description: "Student sorts items into categories.",
    defaultInputMode: "drag_or_tap",
    responseLanguage: "none",
    defaultMarkingMode: "auto_structured",
    requiresRussianTyping: false,
    isExamAligned: false,
    order: 5,
  },
  {
    key: "ordering",
    label: "Ordering",
    description: "Student orders events, words, phrases, or sentences.",
    defaultInputMode: "drag_or_tap",
    responseLanguage: "none",
    defaultMarkingMode: "auto_structured",
    requiresRussianTyping: false,
    isExamAligned: true,
    order: 6,
  },
  {
    key: "word_bank_gap_fill",
    label: "Word-bank gap fill",
    description: "Student fills gaps using provided words or phrases.",
    defaultInputMode: "drag_or_tap",
    responseLanguage: "mixed",
    defaultMarkingMode: "auto_structured",
    requiresRussianTyping: false,
    isExamAligned: true,
    order: 7,
  },
  {
    key: "dropdown_gap_fill",
    label: "Dropdown gap fill",
    description: "Student chooses one option for each gap.",
    defaultInputMode: "select",
    responseLanguage: "mixed",
    defaultMarkingMode: "auto_structured",
    requiresRussianTyping: false,
    isExamAligned: true,
    order: 8,
  },
  {
    key: "table_completion",
    label: "Table completion",
    description: "Student completes table cells, preferably using choices.",
    defaultInputMode: "select",
    responseLanguage: "mixed",
    defaultMarkingMode: "auto_structured",
    requiresRussianTyping: false,
    isExamAligned: true,
    order: 9,
  },
  {
    key: "click_text",
    label: "Click text",
    description: "Student clicks words or phrases in a stimulus text.",
    defaultInputMode: "tap",
    responseLanguage: "none",
    defaultMarkingMode: "auto_structured",
    requiresRussianTyping: false,
    isExamAligned: false,
    order: 10,
  },
  {
    key: "opinion_recognition",
    label: "Opinion recognition",
    description: "Student identifies opinion, attitude, or polarity.",
    defaultInputMode: "select",
    responseLanguage: "none",
    defaultMarkingMode: "auto_structured",
    requiresRussianTyping: false,
    isExamAligned: true,
    order: 11,
  },
  {
    key: "speaker_identification",
    label: "Speaker identification",
    description: "Student links details, opinions, or statements to speakers.",
    defaultInputMode: "select",
    responseLanguage: "none",
    defaultMarkingMode: "auto_structured",
    requiresRussianTyping: false,
    isExamAligned: true,
    order: 12,
  },
  {
    key: "sentence_builder",
    label: "Sentence builder",
    description: "Student builds a sentence from selectable tiles.",
    defaultInputMode: "drag_or_tap",
    responseLanguage: "russian",
    defaultMarkingMode: "auto_normalized_text",
    requiresRussianTyping: false,
    isExamAligned: false,
    order: 13,
  },
  {
    key: "phrase_builder",
    label: "Phrase builder",
    description: "Student builds a phrase from selectable tiles.",
    defaultInputMode: "drag_or_tap",
    responseLanguage: "russian",
    defaultMarkingMode: "auto_normalized_text",
    requiresRussianTyping: false,
    isExamAligned: false,
    order: 14,
  },
  {
    key: "translation_en_ru_tiles",
    label: "Translation into Russian with tiles",
    description: "Student translates into Russian using provided tiles.",
    defaultInputMode: "drag_or_tap",
    responseLanguage: "russian",
    defaultMarkingMode: "auto_normalized_text",
    requiresRussianTyping: false,
    isExamAligned: true,
    order: 15,
  },
  {
    key: "grammar_form_selection",
    label: "Grammar form selection",
    description: "Student chooses the correct grammar form from options.",
    defaultInputMode: "select",
    responseLanguage: "russian",
    defaultMarkingMode: "auto_structured",
    requiresRussianTyping: false,
    isExamAligned: false,
    order: 16,
  },
  {
    key: "verb_form_selection",
    label: "Verb form selection",
    description: "Student chooses the correct verb form from options.",
    defaultInputMode: "select",
    responseLanguage: "russian",
    defaultMarkingMode: "auto_structured",
    requiresRussianTyping: false,
    isExamAligned: false,
    order: 17,
  },
  {
    key: "sentence_transformation_tiles",
    label: "Sentence transformation with tiles",
    description: "Student transforms a sentence using provided words or phrases.",
    defaultInputMode: "drag_or_tap",
    responseLanguage: "russian",
    defaultMarkingMode: "auto_normalized_text",
    requiresRussianTyping: false,
    isExamAligned: false,
    order: 18,
  },
  {
    key: "error_spotting",
    label: "Error spotting",
    description: "Student identifies an error in a word, phrase, or sentence.",
    defaultInputMode: "tap",
    responseLanguage: "none",
    defaultMarkingMode: "auto_structured",
    requiresRussianTyping: false,
    isExamAligned: false,
    order: 19,
  },
  {
    key: "error_correction_selection",
    label: "Error correction selection",
    description: "Student corrects an error by selecting from provided options.",
    defaultInputMode: "select",
    responseLanguage: "russian",
    defaultMarkingMode: "auto_structured",
    requiresRussianTyping: false,
    isExamAligned: false,
    order: 20,
  },
  {
    key: "short_answer_en",
    label: "Short answer in English",
    description: "Student types a concise English answer.",
    defaultInputMode: "type_english",
    responseLanguage: "english",
    defaultMarkingMode: "auto_normalized_text",
    requiresRussianTyping: false,
    isExamAligned: true,
    order: 21,
  },
  {
    key: "note_completion_en",
    label: "Note completion in English",
    description: "Student types short English notes or details.",
    defaultInputMode: "type_english",
    responseLanguage: "english",
    defaultMarkingMode: "auto_normalized_text",
    requiresRussianTyping: false,
    isExamAligned: true,
    order: 22,
  },
  {
    key: "translation_ru_en",
    label: "Translation into English",
    description: "Student translates Russian text into English.",
    defaultInputMode: "type_english",
    responseLanguage: "english",
    defaultMarkingMode: "teacher_marked",
    requiresRussianTyping: false,
    isExamAligned: true,
    order: 23,
  },
  {
    key: "summary_answer_en",
    label: "Summary answer in English",
    description: "Student writes a concise English summary of meaning.",
    defaultInputMode: "type_english",
    responseLanguage: "english",
    defaultMarkingMode: "teacher_marked",
    requiresRussianTyping: false,
    isExamAligned: true,
    order: 24,
  },
  {
    key: "writing_upload",
    label: "Writing upload",
    description: "Student uploads handwritten writing for review.",
    defaultInputMode: "upload",
    responseLanguage: "russian",
    defaultMarkingMode: "teacher_marked",
    requiresRussianTyping: false,
    isExamAligned: true,
    order: 25,
  },
  {
    key: "writing_draft_optional",
    label: "Optional writing draft",
    description: "Student may type a draft or planning notes.",
    defaultInputMode: "type_russian_optional",
    responseLanguage: "mixed",
    defaultMarkingMode: "teacher_marked",
    requiresRussianTyping: false,
    isExamAligned: true,
    order: 26,
  },
  {
    key: "speaking_recording",
    label: "Speaking recording",
    description: "Student records spoken Russian for review.",
    defaultInputMode: "record",
    responseLanguage: "russian",
    defaultMarkingMode: "teacher_marked",
    requiresRussianTyping: false,
    isExamAligned: true,
    order: 27,
  },
  {
    key: "speaking_prep_notes",
    label: "Speaking prep notes",
    description: "Student prepares notes before a speaking response.",
    defaultInputMode: "type_english",
    responseLanguage: "english",
    defaultMarkingMode: "manual",
    requiresRussianTyping: false,
    isExamAligned: true,
    order: 28,
  },
  {
    key: "role_play_response",
    label: "Role play response",
    description: "Student responds to role-play prompts.",
    defaultInputMode: "record",
    responseLanguage: "russian",
    defaultMarkingMode: "teacher_marked",
    requiresRussianTyping: false,
    isExamAligned: true,
    order: 29,
  },
  {
    key: "photo_card_response",
    label: "Photo card response",
    description: "Student responds to photo-card prompts.",
    defaultInputMode: "record",
    responseLanguage: "russian",
    defaultMarkingMode: "teacher_marked",
    requiresRussianTyping: false,
    isExamAligned: true,
    order: 30,
  },
  {
    key: "conversation_response",
    label: "Conversation response",
    description: "Student responds to conversation prompts.",
    defaultInputMode: "record",
    responseLanguage: "russian",
    defaultMarkingMode: "teacher_marked",
    requiresRussianTyping: false,
    isExamAligned: true,
    order: 31,
  },
  {
    key: "manual_marked_response",
    label: "Manual marked response",
    description: "Generic migration-only response for unusual tasks.",
    defaultInputMode: "manual",
    responseLanguage: "mixed",
    defaultMarkingMode: "manual",
    requiresRussianTyping: false,
    isExamAligned: false,
    order: 32,
  },
] as const satisfies readonly QuestionInteractionType[];
