import type { ExistingQuestionTypeCompatibility } from "./question-taxonomy-types";

export const EXISTING_QUESTION_SET_COMPATIBILITY = [
  {
    sourceSystem: "question_set",
    existingType: "multiple_choice",
    recommendedInteractionTypes: ["single_choice"],
    status: "covered",
    russianTypingRisk: "none",
    notes: "Current reusable question-set MCQ maps cleanly to single choice.",
  },
  {
    sourceSystem: "question_set",
    existingType: "short_answer",
    recommendedInteractionTypes: ["short_answer_en", "note_completion_en"],
    status: "covered",
    russianTypingRisk: "medium",
    notes: "Keep for English responses. Avoid authoring Russian typed answers by default.",
  },
  {
    sourceSystem: "question_set",
    existingType: "translation",
    existingAnswerStrategy: "text_input",
    recommendedInteractionTypes: ["translation_ru_en", "manual_marked_response"],
    status: "partial",
    russianTypingRisk: "high",
    notes: "Safe for Russian-to-English. English-to-Russian text input should become optional or upload-based.",
  },
  {
    sourceSystem: "question_set",
    existingType: "translation",
    existingAnswerStrategy: "sentence_builder",
    recommendedInteractionTypes: ["translation_en_ru_tiles", "sentence_builder"],
    status: "covered",
    russianTypingRisk: "none",
    notes: "Promote this metadata strategy to a first-class interaction.",
  },
  {
    sourceSystem: "question_set",
    existingType: "translation",
    existingAnswerStrategy: "selection_based",
    recommendedInteractionTypes: [
      "dropdown_gap_fill",
      "grammar_form_selection",
      "word_bank_gap_fill",
    ],
    status: "partial",
    russianTypingRisk: "none",
    notes: "Useful digital-first pattern, but currently hidden inside translation metadata.",
  },
  {
    sourceSystem: "question_set",
    existingType: "translation",
    existingAnswerStrategy: "upload_required",
    recommendedInteractionTypes: ["writing_upload"],
    status: "needs_new_interaction",
    russianTypingRisk: "none",
    notes: "Currently renders as an unsupported placeholder.",
  },
] as const satisfies readonly ExistingQuestionTypeCompatibility[];

export const EXISTING_MOCK_EXAM_COMPATIBILITY = [
  {
    sourceSystem: "mock_exam",
    existingType: "multiple_choice",
    recommendedInteractionTypes: ["single_choice"],
    status: "covered",
    russianTypingRisk: "none",
    notes: "Current mock exam response UI supports radio selection.",
  },
  {
    sourceSystem: "mock_exam",
    existingType: "multiple_response",
    recommendedInteractionTypes: ["multi_select"],
    status: "covered",
    russianTypingRisk: "none",
    notes: "Current mock exam response UI supports checkboxes.",
  },
  {
    sourceSystem: "mock_exam",
    existingType: "short_answer",
    recommendedInteractionTypes: ["short_answer_en"],
    status: "covered",
    russianTypingRisk: "medium",
    notes: "Suitable for English short answers. Should not be the default for Russian answers.",
  },
  {
    sourceSystem: "mock_exam",
    existingType: "gap_fill",
    recommendedInteractionTypes: ["word_bank_gap_fill", "dropdown_gap_fill"],
    status: "needs_new_interaction",
    russianTypingRisk: "medium",
    notes: "Current UI uses text inputs; future UI should offer selectable words by default.",
  },
  {
    sourceSystem: "mock_exam",
    existingType: "matching",
    recommendedInteractionTypes: ["matching", "speaker_identification"],
    status: "covered",
    russianTypingRisk: "none",
    notes: "Current mock UI supports select-based matching; make shared later.",
  },
  {
    sourceSystem: "mock_exam",
    existingType: "sequencing",
    recommendedInteractionTypes: ["ordering"],
    status: "needs_new_interaction",
    russianTypingRisk: "none",
    notes: "Current UI asks for comma-separated numbers; replace with tap/drag ordering.",
  },
  {
    sourceSystem: "mock_exam",
    existingType: "opinion_recognition",
    recommendedInteractionTypes: ["opinion_recognition"],
    status: "covered",
    russianTypingRisk: "none",
    notes: "Current mock UI supports statement-level select controls.",
  },
  {
    sourceSystem: "mock_exam",
    existingType: "true_false_not_mentioned",
    recommendedInteractionTypes: ["true_false_not_mentioned"],
    status: "covered",
    russianTypingRisk: "none",
    notes: "Current mock UI supports statement-level select controls.",
  },
  {
    sourceSystem: "mock_exam",
    existingType: "translation_into_english",
    recommendedInteractionTypes: ["translation_ru_en"],
    status: "partial",
    russianTypingRisk: "none",
    notes: "Current UI falls back to textarea and manual marking.",
  },
  {
    sourceSystem: "mock_exam",
    existingType: "translation_into_russian",
    recommendedInteractionTypes: ["translation_en_ru_tiles", "writing_upload"],
    status: "needs_new_interaction",
    russianTypingRisk: "high",
    notes: "Avoid default typed Cyrillic; use tiles for controlled practice and uploads for exam writing.",
  },
  {
    sourceSystem: "mock_exam",
    existingType: "writing_task",
    recommendedInteractionTypes: ["writing_upload", "writing_draft_optional"],
    status: "needs_new_interaction",
    russianTypingRisk: "high",
    notes: "Needs upload workflow and rubric metadata.",
  },
  {
    sourceSystem: "mock_exam",
    existingType: "simple_sentences",
    recommendedInteractionTypes: [
      "writing_upload",
      "sentence_builder",
      "writing_draft_optional",
    ],
    status: "partial",
    russianTypingRisk: "high",
    notes: "Can be scaffolded digitally before becoming an upload or optional draft task.",
  },
  {
    sourceSystem: "mock_exam",
    existingType: "short_paragraph",
    recommendedInteractionTypes: ["writing_upload", "writing_draft_optional"],
    status: "needs_new_interaction",
    russianTypingRisk: "high",
    notes: "Needs writing workflow and rubric metadata.",
  },
  {
    sourceSystem: "mock_exam",
    existingType: "extended_writing",
    recommendedInteractionTypes: ["writing_upload", "writing_draft_optional"],
    status: "needs_new_interaction",
    russianTypingRisk: "high",
    notes: "Needs writing workflow and rubric metadata.",
  },
  {
    sourceSystem: "mock_exam",
    existingType: "role_play",
    recommendedInteractionTypes: [
      "role_play_response",
      "speaking_prep_notes",
      "speaking_recording",
    ],
    status: "needs_new_interaction",
    russianTypingRisk: "none",
    notes: "Needs speaking prep and recording workflow.",
  },
  {
    sourceSystem: "mock_exam",
    existingType: "photo_card",
    recommendedInteractionTypes: [
      "photo_card_response",
      "speaking_prep_notes",
      "speaking_recording",
    ],
    status: "needs_new_interaction",
    russianTypingRisk: "none",
    notes: "Needs image prompt, prep notes, and recording workflow.",
  },
  {
    sourceSystem: "mock_exam",
    existingType: "conversation",
    recommendedInteractionTypes: ["conversation_response", "speaking_recording"],
    status: "needs_new_interaction",
    russianTypingRisk: "none",
    notes: "Needs speaking response workflow.",
  },
  {
    sourceSystem: "mock_exam",
    existingType: "sentence_builder",
    recommendedInteractionTypes: ["sentence_builder", "translation_en_ru_tiles"],
    status: "partial",
    russianTypingRisk: "none",
    notes: "Auto-marking exists, but response UI currently falls back to textarea.",
  },
  {
    sourceSystem: "mock_exam",
    existingType: "note_completion",
    recommendedInteractionTypes: ["note_completion_en", "word_bank_gap_fill"],
    status: "partial",
    russianTypingRisk: "low",
    notes: "Current UI uses text inputs; choices should be available for Russian content.",
  },
  {
    sourceSystem: "mock_exam",
    existingType: "listening_comprehension",
    recommendedInteractionTypes: ["manual_marked_response"],
    status: "partial",
    russianTypingRisk: "none",
    notes: "Should become a listening task parent with child interaction questions.",
  },
  {
    sourceSystem: "mock_exam",
    existingType: "reading_comprehension",
    recommendedInteractionTypes: ["manual_marked_response"],
    status: "partial",
    russianTypingRisk: "none",
    notes: "Should become a reading task parent with child interaction questions.",
  },
  {
    sourceSystem: "mock_exam",
    existingType: "other",
    recommendedInteractionTypes: ["manual_marked_response"],
    status: "migration_only",
    russianTypingRisk: "medium",
    notes: "Keep only as an escape hatch during migration.",
  },
] as const satisfies readonly ExistingQuestionTypeCompatibility[];

export const EXISTING_QUESTION_TYPE_COMPATIBILITY = [
  ...EXISTING_QUESTION_SET_COMPATIBILITY,
  ...EXISTING_MOCK_EXAM_COMPATIBILITY,
] as const satisfies readonly ExistingQuestionTypeCompatibility[];

