import type { QuestionInteractionType } from "./question-taxonomy-types";

export const QUESTION_TEACHER_MARKED_INTERACTION_TYPES = [
  {
    key: "translation_ru_en",
    label: "Translation into English",
    description: "Student translates Russian text into English.",
    defaultInputMode: "type_english",
    responseLanguage: "english",
    defaultMarkingMode: "teacher_marked",
    requiresRussianTyping: false,
    isExamAligned: true,
    order: 23,
  },
  {
    key: "summary_answer_en",
    label: "Summary answer in English",
    description: "Student writes a concise English summary of meaning.",
    defaultInputMode: "type_english",
    responseLanguage: "english",
    defaultMarkingMode: "teacher_marked",
    requiresRussianTyping: false,
    isExamAligned: true,
    order: 24,
  },
  {
    key: "writing_upload",
    label: "Writing upload",
    description: "Student uploads handwritten writing for review.",
    defaultInputMode: "upload",
    responseLanguage: "russian",
    defaultMarkingMode: "teacher_marked",
    requiresRussianTyping: false,
    isExamAligned: true,
    order: 25,
  },
  {
    key: "writing_draft_optional",
    label: "Optional writing draft",
    description: "Student may type a draft or planning notes.",
    defaultInputMode: "type_russian_optional",
    responseLanguage: "mixed",
    defaultMarkingMode: "teacher_marked",
    requiresRussianTyping: false,
    isExamAligned: true,
    order: 26,
  },
  {
    key: "speaking_recording",
    label: "Speaking recording",
    description: "Student records spoken Russian for review.",
    defaultInputMode: "record",
    responseLanguage: "russian",
    defaultMarkingMode: "teacher_marked",
    requiresRussianTyping: false,
    isExamAligned: true,
    order: 27,
  },
  {
    key: "speaking_prep_notes",
    label: "Speaking prep notes",
    description: "Student prepares notes before a speaking response.",
    defaultInputMode: "type_english",
    responseLanguage: "english",
    defaultMarkingMode: "manual",
    requiresRussianTyping: false,
    isExamAligned: true,
    order: 28,
  },
  {
    key: "role_play_response",
    label: "Role play response",
    description: "Student responds to role-play prompts.",
    defaultInputMode: "record",
    responseLanguage: "russian",
    defaultMarkingMode: "teacher_marked",
    requiresRussianTyping: false,
    isExamAligned: true,
    order: 29,
  },
  {
    key: "photo_card_response",
    label: "Photo card response",
    description: "Student responds to photo-card prompts.",
    defaultInputMode: "record",
    responseLanguage: "russian",
    defaultMarkingMode: "teacher_marked",
    requiresRussianTyping: false,
    isExamAligned: true,
    order: 30,
  },
  {
    key: "conversation_response",
    label: "Conversation response",
    description: "Student responds to conversation prompts.",
    defaultInputMode: "record",
    responseLanguage: "russian",
    defaultMarkingMode: "teacher_marked",
    requiresRussianTyping: false,
    isExamAligned: true,
    order: 31,
  },
  {
    key: "manual_marked_response",
    label: "Manual marked response",
    description: "Generic migration-only response for unusual tasks.",
    defaultInputMode: "manual",
    responseLanguage: "mixed",
    defaultMarkingMode: "manual",
    requiresRussianTyping: false,
    isExamAligned: false,
    order: 32,
  },
] as const satisfies readonly QuestionInteractionType[];
