export const VOCABULARY_TAGS = [
  {
    key: "high_frequency_common_verbs",
    label: "Common verbs",
    domain: "high_frequency",
    tier: "both",
    order: 1,
  },
  {
    key: "high_frequency_common_adjectives",
    label: "Common adjectives",
    domain: "high_frequency",
    tier: "both",
    order: 2,
  },
  {
    key: "high_frequency_common_adverbs",
    label: "Common adverbs",
    domain: "high_frequency",
    tier: "both",
    order: 3,
  },
  {
    key: "high_frequency_prepositions",
    label: "Prepositions",
    domain: "high_frequency",
    tier: "both",
    order: 4,
  },
  {
    key: "high_frequency_colours",
    label: "Colours",
    domain: "high_frequency",
    tier: "both",
    order: 5,
  },
  {
    key: "high_frequency_numbers",
    label: "Numbers",
    domain: "high_frequency",
    tier: "both",
    order: 6,
  },
  {
    key: "high_frequency_time",
    label: "Time expressions",
    domain: "high_frequency",
    tier: "both",
    order: 7,
  },
  {
    key: "high_frequency_countries_and_nationalities",
    label: "Countries and nationalities",
    domain: "high_frequency",
    tier: "both",
    order: 8,
  },
  {
    key: "high_frequency_social_conventions",
    label: "Social conventions",
    domain: "high_frequency",
    tier: "both",
    order: 9,
  },

  {
    key: "identity_and_culture_family_and_relationships",
    label: "Family and relationships",
    domain: "topic_specific",
    themeKey: "identity_and_culture",
    tier: "both",
    order: 10,
  },
  {
    key: "identity_and_culture_food_and_drink",
    label: "Food and drink",
    domain: "topic_specific",
    themeKey: "identity_and_culture",
    tier: "both",
    order: 11,
  },
  {
    key: "identity_and_culture_clothes_and_style",
    label: "Clothes and style",
    domain: "topic_specific",
    themeKey: "identity_and_culture",
    tier: "both",
    order: 12,
  },

  {
    key: "local_area_holiday_travel",
    label: "Holiday and travel",
    domain: "topic_specific",
    themeKey: "local_area_holiday_travel",
    tier: "both",
    order: 13,
  },
  {
    key: "travel_transactions",
    label: "Travel transactions",
    domain: "topic_specific",
    themeKey: "local_area_holiday_travel",
    tier: "both",
    order: 14,
  },

  {
    key: "school_life",
    label: "School life",
    domain: "topic_specific",
    themeKey: "school",
    tier: "both",
    order: 15,
  },
  {
    key: "school_activities",
    label: "School activities",
    domain: "topic_specific",
    themeKey: "school",
    tier: "both",
    order: 16,
  },

  {
    key: "future_study_and_work",
    label: "Future study and work",
    domain: "topic_specific",
    themeKey: "future_aspirations_study_work",
    tier: "both",
    order: 17,
  },

  {
    key: "international_events_and_causes",
    label: "International events and causes",
    domain: "topic_specific",
    themeKey: "international_global_dimension",
    tier: "both",
    order: 18,
  },
  {
    key: "environmental_issues",
    label: "Environmental issues",
    domain: "topic_specific",
    themeKey: "international_global_dimension",
    tier: "both",
    order: 19,
  },
] as const;

export type VocabularyTagKey = (typeof VOCABULARY_TAGS)[number]["key"];
