import {
  AlertCircle,
  AlertTriangle,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  AudioLines,
  BadgeCheck,
  Blocks,
  BookA,
  BookMarked,
  BookOpen,
  BookText,
  Brain,
  CalendarDays,
  Check,
  CheckCircle2,
  CheckSquare,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CircleHelp,
  CircleDashed,
  ClipboardCheck,
  ClipboardList,
  Clock,
  Component,
  Copy,
  Download,
  Eye,
  EyeOff,
  ExternalLink,
  FileQuestion,
  FileText,
  Filter,
  Folder,
  FolderOpen,
  GraduationCap,
  GripVertical,
  History,
  Headphones,
  Heading1,
  Heading2,
  House,
  Image as ImageIcon,
  Info,
  Languages,
  LayoutGrid,
  Layers,
  Lightbulb,
  List,
  Lock,
  Megaphone,
  Menu,
  MessageSquare,
  Mic,
  Minus,
  Moon,
  NotebookText,
  Palette,
  PanelLeft,
  PanelsTopLeft,
  PenSquare,
  Pencil,
  Plus,
  RefreshCw,
  ReceiptText,
  Save,
  School,
  ScrollText,
  Search,
  Settings,
  SlidersHorizontal,
  Sparkles,
  SquarePen,
  Star,
  Sun,
  Table2,
  Tags,
  Trash2,
  Type,
  Unlock,
  Upload,
  User,
  UserCheck,
  UserCog,
  UserRoundCheck,
  UserX,
  Users,
  WandSparkles,
  WalletCards,
  X,
} from "lucide-react";

export const appIcons = {
  home: House,
  dashboard: LayoutGrid,
  courses: BookOpen,
  lessons: BookOpen,
  lesson: FileText,
  lessonContent: BookText,
  assignments: ClipboardList,
  translation: Languages,
  listening: Headphones,
  audio: AudioLines,
  vocabulary: Tags,
  vocabularySet: BookMarked,
  grammar: BookA,
  pastPapers: ScrollText,
  exam: ClipboardCheck,
  mockExam: FileQuestion,
  image: ImageIcon,
  file: FileText,
  sun: Sun,
  moon: Moon,
  completed: CheckCircle2,
  pending: Clock,
  active: CheckCircle2,
  inactive: CircleDashed,
  submitted: Upload,
  marked: BadgeCheck,
  published: BadgeCheck,
  draft: CircleDashed,
  locked: Lock,
  unlocked: Unlock,
  lock: Lock,
  upload: Upload,
  download: Download,
  calendar: CalendarDays,
  chat: MessageSquare,
  help: CircleHelp,
  search: Search,
  filter: Filter,
  preview: Eye,
  hidden: EyeOff,
  externalLink: ExternalLink,
  edit: SquarePen,
  write: PenSquare,
  create: Plus,
  delete: Trash2,
  duplicate: Copy,
  reorder: GripVertical,
  settings: Settings,
  admin: UserCog,
  teacher: UserRoundCheck,
  student: GraduationCap,
  user: User,
  users: Users,
  back: ChevronLeft,
  next: ChevronRight,
  up: ChevronUp,
  down: ChevronDown,
  uiLab: WandSparkles,
  layers: Layers,
  star: Star,

  chevronRight: ChevronRight,
  chevronDown: ChevronDown,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  arrowUp: ArrowUp,
  arrowDown: ArrowDown,

  save: Save,
  confirm: Check,
  cancel: X,
  refresh: RefreshCw,
  sync: RefreshCw,
  history: History,

  modules: Layers,
  folderOpen: FolderOpen,
  folder: Folder,
  list: List,
  table: Table2,
  blocks: Blocks,
  menu: Menu,

  learning: GraduationCap,
  school: School,
  brain: Brain,
  idea: Lightbulb,
  language: Languages,

  userCheck: UserCheck,
  userX: UserX,

  warning: AlertTriangle,
  info: Info,
  alert: AlertCircle,
  error: AlertCircle,
  success: CheckCircle2,

  component: Component,
  palette: Palette,

  speaking: Mic,

  question: CircleHelp,
  questionSet: FileQuestion,
  exercise: CheckSquare,
  text: Type,
  note: NotebookText,
  heading: Heading1,
  subheader: Heading2,
  divider: Minus,
  callout: Megaphone,
  examTip: Lightbulb,
  pencil: Pencil,

  billing: ReceiptText,
  pricing: WalletCards,

  navigation: PanelLeft,
  header: PanelsTopLeft,
  layout: PanelsTopLeft,
  surfaces: Layers,
  forms: SlidersHorizontal,
  feedback: Sparkles,
} as const;

export type AppIconKey = keyof typeof appIcons;

export const curatedLucideIconNames = new Set<string>([
  "House",
  "LayoutGrid",
  "BookOpen",
  "FileText",
  "BookText",
  "ClipboardList",
  "Languages",
  "Headphones",
  "AudioLines",
  "BookA",
  "BookMarked",
  "Tags",
  "ScrollText",
  "ClipboardCheck",
  "FileQuestion",
  "Image",
  "CheckCircle2",
  "Clock",
  "BadgeCheck",
  "CircleDashed",
  "Lock",
  "Unlock",
  "Upload",
  "Download",
  "CalendarDays",
  "MessageSquare",
  "CircleHelp",
  "Search",
  "Filter",
  "Eye",
  "EyeOff",
  "ExternalLink",
  "SquarePen",
  "PenSquare",
  "Plus",
  "Trash2",
  "Copy",
  "GripVertical",
  "Settings",
  "UserCog",
  "UserRoundCheck",
  "User",
  "Users",
  "ChevronLeft",
  "ChevronRight",
  "ChevronUp",
  "ChevronDown",
  "WandSparkles",
  "ArrowLeft",
  "ArrowRight",
  "ArrowUp",
  "ArrowDown",
  "Save",
  "Check",
  "X",
  "RefreshCw",
  "History",
  "Layers",
  "FolderOpen",
  "Folder",
  "List",
  "Table2",
  "Blocks",
  "Menu",
  "GraduationCap",
  "School",
  "Brain",
  "Lightbulb",
  "UserCheck",
  "UserX",
  "AlertTriangle",
  "Info",
  "AlertCircle",
  "Component",
  "Palette",
  "Mic",
  "CheckSquare",
  "Type",
  "NotebookText",
  "Heading1",
  "Heading2",
  "Minus",
  "Megaphone",
  "Pencil",
  "ReceiptText",
  "WalletCards",
  "Sun",
  "Moon",
  "SlidersHorizontal",
  "PanelLeft",
  "PanelsTopLeft",
  "Sparkles",
  "Star",
]);
