begin;

alter table public.vocabulary_items
  add column if not exists spec_russian text;

insert into public.vocabulary_import_sources (
  source_key,
  title,
  source_version,
  publisher,
  notes
)
values (
  'pearson_edexcel_gcse_russian_1ru0',
  'Pearson Edexcel GCSE Russian vocabulary specification',
  '1RU0',
  'Pearson Edexcel',
  'Imported GCSE Russian specification vocabulary. Includes Section 1: High-frequency language and Section 2: Topic-specific vocabulary sets.'
)
on conflict (source_key) do update
set
  title = excluded.title,
  source_version = excluded.source_version,
  publisher = excluded.publisher,
  notes = excluded.notes,
  updated_at = now();

with upserted_set as (
  insert into public.vocabulary_sets (
    slug,
    title,
    description,
    theme_key,
    topic_key,
    tier,
    list_mode,
    set_type,
    default_display_variant,
    is_published,
    sort_order,
    source_key,
    source_version,
    import_key
  )
  values (
    'local-area-holiday-and-travel',
    'Local area, holiday and travel',
    'Spec-required topic-specific GCSE Russian vocabulary for local area, holiday and travel.',
    'local_area_holiday_travel',
    'local_area_holiday_travel',
    'both',
    'spec_only',
    'specification',
    'single_column',
    true,
    400,
    'pearson_edexcel_gcse_russian_1ru0',
    '1RU0',
    'section-2:local-area-holiday-and-travel'
  )
  on conflict (source_key, import_key)
  where source_key is not null and import_key is not null
  do update
  set
    slug = excluded.slug,
    title = excluded.title,
    description = excluded.description,
    theme_key = excluded.theme_key,
    topic_key = excluded.topic_key,
    tier = excluded.tier,
    list_mode = excluded.list_mode,
    set_type = excluded.set_type,
    default_display_variant = excluded.default_display_variant,
    is_published = excluded.is_published,
    sort_order = excluded.sort_order,
    source_version = excluded.source_version,
    updated_at = now()
  returning id
),
upserted_list as (
  insert into public.vocabulary_lists (
    vocabulary_set_id,
    slug,
    title,
    description,
    theme_key,
    topic_key,
    category_key,
    tier,
    list_mode,
    default_display_variant,
    is_published,
    sort_order,
    source_key,
    source_version,
    source_section_ref,
    import_key
  )
  select
    id,
    'foundation',
    'Foundation tier',
    'Foundation tier vocabulary for local area, holiday and travel.',
    'local_area_holiday_travel',
    'local_area_holiday_travel',
    'local_area_holiday_travel',
    'foundation',
    'spec_only',
    'single_column',
    true,
    400,
    'pearson_edexcel_gcse_russian_1ru0',
    '1RU0',
    'Section 2: Topic-specific vocabulary / Local area, holiday and travel / Foundation tier',
    'section-2:local-area-holiday-and-travel:foundation:list'
  from upserted_set
  on conflict (source_key, import_key)
  where source_key is not null and import_key is not null
  do update
  set
    title = excluded.title,
    description = excluded.description,
    theme_key = excluded.theme_key,
    topic_key = excluded.topic_key,
    category_key = excluded.category_key,
    tier = excluded.tier,
    list_mode = excluded.list_mode,
    default_display_variant = excluded.default_display_variant,
    is_published = excluded.is_published,
    sort_order = excluded.sort_order,
    source_version = excluded.source_version,
    source_section_ref = excluded.source_section_ref,
    updated_at = now()
  returning id, vocabulary_set_id
),
raw_items (
  position,
  english,
  russian,
  spec_russian,
  part_of_speech,
  gender,
  aspect,
  is_reflexive
) as (
  values
    (1, $$accommodation$$, $$жильё$$, $$жильё$$, 'noun', 'neuter', 'not_applicable', false),
    (2, $$air$$, $$воздух$$, $$воздух$$, 'noun', 'masculine', 'not_applicable', false),
    (3, $$airport$$, $$аэропорт$$, $$аэропорт$$, 'noun', 'masculine', 'not_applicable', false),
    (4, $$aquarium$$, $$аквариум$$, $$аквариум$$, 'noun', 'masculine', 'not_applicable', false),
    (5, $$area (in town)$$, $$(городской) район$$, $$(городской) район$$, 'noun', 'masculine', 'not_applicable', false),
    (6, $$art gallery$$, $$галерея$$, $$галерея$$, 'noun', 'feminine', 'not_applicable', false),
    (7, $$atlas$$, $$атлас$$, $$атлас$$, 'noun', 'masculine', 'not_applicable', false),
    (8, $$back$$, $$обратно$$, $$обратно$$, 'adverb', 'not_applicable', 'not_applicable', false),
    (9, $$balcony$$, $$балкон$$, $$балкон$$, 'noun', 'masculine', 'not_applicable', false),
    (10, $$bank$$, $$банк$$, $$банк$$, 'noun', 'masculine', 'not_applicable', false),
    (11, $$bar$$, $$бар$$, $$бар$$, 'noun', 'masculine', 'not_applicable', false),
    (12, $$barbecue$$, $$барбекю$$, $$барбекю$$, 'noun', 'neuter', 'not_applicable', false),
    (13, $$bath$$, $$ванна$$, $$ванна$$, 'noun', 'feminine', 'not_applicable', false),
    (14, $$bathroom$$, $$ванная$$, $$ванная$$, 'noun', 'feminine', 'not_applicable', false),
    (15, $$beach$$, $$пляж$$, $$пляж$$, 'noun', 'masculine', 'not_applicable', false),
    (16, $$bed$$, $$кровать$$, $$кровать$$, 'noun', 'feminine', 'not_applicable', false),
    (17, $$bicycle/bike$$, $$велосипед$$, $$велосипед$$, 'noun', 'masculine', 'not_applicable', false),
    (18, $$boat$$, $$лодка$$, $$лодка$$, 'noun', 'feminine', 'not_applicable', false),
    (19, $$bowling alley$$, $$боулинг$$, $$боулинг$$, 'noun', 'masculine', 'not_applicable', false),
    (20, $$brand/make$$, $$марка$$, $$марка$$, 'noun', 'feminine', 'not_applicable', false),
    (21, $$bridge$$, $$мост$$, $$мост$$, 'noun', 'masculine', 'not_applicable', false),
    (22, $$brochure$$, $$брошюра$$, $$брошюра$$, 'noun', 'feminine', 'not_applicable', false),
    (23, $$building$$, $$здание$$, $$здание$$, 'noun', 'neuter', 'not_applicable', false),
    (24, $$bus (by bus)$$, $$автобус (автобусом)$$, $$автобус (автобусом)$$, 'noun', 'masculine', 'not_applicable', false),
    (25, $$bus stop$$, $$автобусная остановка$$, $$автобусная остановка$$, 'noun', 'feminine', 'not_applicable', false),
    (26, $$bus/coach station$$, $$автовокзал$$, $$автовокзал$$, 'noun', 'masculine', 'not_applicable', false),
    (27, $$business$$, $$бизнес$$, $$бизнес$$, 'noun', 'masculine', 'not_applicable', false),
    (28, $$café$$, $$кафе$$, $$кафе$$, 'noun', 'neuter', 'not_applicable', false),
    (29, $$camp$$, $$лагерь$$, $$лагерь m$$, 'noun', 'masculine', 'not_applicable', false),
    (30, $$campsite$$, $$кемпинг$$, $$кемпинг$$, 'noun', 'masculine', 'not_applicable', false),
    (31, $$capital city$$, $$столица$$, $$столица$$, 'noun', 'feminine', 'not_applicable', false),
    (32, $$car$$, $$машина$$, $$машина$$, 'noun', 'feminine', 'not_applicable', false),
    (33, $$car, automobile$$, $$автомобиль$$, $$автомобиль$$, 'noun', 'masculine', 'not_applicable', false),
    (34, $$cathedral$$, $$собор$$, $$собор$$, 'noun', 'masculine', 'not_applicable', false),
    (35, $$centre$$, $$центр$$, $$центр$$, 'noun', 'masculine', 'not_applicable', false),
    (36, $$chemist's$$, $$аптека$$, $$аптека$$, 'noun', 'feminine', 'not_applicable', false),
    (37, $$cheque; receipt$$, $$чек$$, $$чек$$, 'noun', 'masculine', 'not_applicable', false),
    (38, $$church$$, $$церковь$$, $$церковь$$, 'noun', 'feminine', 'not_applicable', false),
    (39, $$cinema (building)$$, $$кинотеатр$$, $$кинотеатр$$, 'noun', 'masculine', 'not_applicable', false),
    (40, $$circus$$, $$цирк$$, $$цирк$$, 'noun', 'masculine', 'not_applicable', false),
    (41, $$closed$$, $$закрыт$$, $$закрыт$$, 'adjective', 'not_applicable', 'not_applicable', false),
    (42, $$coach$$, $$автобус$$, $$автобус$$, 'noun', 'masculine', 'not_applicable', false),
    (43, $$coast$$, $$берег моря$$, $$берег моря$$, 'noun', 'masculine', 'not_applicable', false),
    (44, $$concert$$, $$концерт$$, $$концерт$$, 'noun', 'masculine', 'not_applicable', false),
    (45, $$country (i.e. nation)$$, $$страна$$, $$страна$$, 'noun', 'feminine', 'not_applicable', false),
    (46, $$countryside$$, $$деревня$$, $$деревня$$, 'noun', 'feminine', 'not_applicable', false),
    (47, $$credit card$$, $$кредитная карточка$$, $$кредитная карточка$$, 'noun', 'feminine', 'not_applicable', false),
    (48, $$department (in a shop)$$, $$отдел$$, $$отдел$$, 'noun', 'masculine', 'not_applicable', false),
    (49, $$department store$$, $$универмаг$$, $$универмаг$$, 'noun', 'masculine', 'not_applicable', false),
    (50, $$destination$$, $$место назначения$$, $$место назначения$$, 'noun', 'neuter', 'not_applicable', false),
    (51, $$direct$$, $$прямой$$, $$прямой$$, 'adjective', 'not_applicable', 'not_applicable', false),
    (52, $$disco$$, $$дискотека$$, $$дискотека$$, 'noun', 'feminine', 'not_applicable', false),
    (53, $$door$$, $$дверь$$, $$дверь$$, 'noun', 'feminine', 'not_applicable', false),
    (54, $$entrance$$, $$вход$$, $$вход$$, 'noun', 'masculine', 'not_applicable', false),
    (55, $$exit$$, $$выход$$, $$выход$$, 'noun', 'masculine', 'not_applicable', false),
    (56, $$experience$$, $$опыт$$, $$опыт$$, 'noun', 'masculine', 'not_applicable', false),
    (57, $$fact$$, $$факт$$, $$факт$$, 'noun', 'masculine', 'not_applicable', false),
    (58, $$factory$$, $$завод$$, $$завод$$, 'noun', 'masculine', 'not_applicable', false),
    (59, $$factory$$, $$фабрика$$, $$фабрика$$, 'noun', 'feminine', 'not_applicable', false),
    (60, $$farm$$, $$ферма$$, $$ферма$$, 'noun', 'feminine', 'not_applicable', false),
    (61, $$festival$$, $$фестиваль$$, $$фестиваль$$, 'noun', 'masculine', 'not_applicable', false),
    (62, $$flight tickets$$, $$авиабилеты$$, $$авиабилеты$$, 'noun', 'plural_only', 'not_applicable', false),
    (63, $$floor (1st, 2nd)$$, $$этаж$$, $$этаж$$, 'noun', 'masculine', 'not_applicable', false),
    (64, $$form$$, $$бланк$$, $$бланк$$, 'noun', 'masculine', 'not_applicable', false),
    (65, $$fountain$$, $$фонтан$$, $$фонтан$$, 'noun', 'masculine', 'not_applicable', false),
    (66, $$ground floor$$, $$первый этаж$$, $$первый этаж$$, 'noun', 'masculine', 'not_applicable', false),
    (67, $$guest$$, $$гость$$, $$гость$$, 'noun', 'masculine', 'not_applicable', false),
    (68, $$guide$$, $$гид / экскурсовод$$, $$гид, экскурсовод$$, 'noun', 'masculine', 'not_applicable', false),
    (69, $$guided tour$$, $$экскурсия$$, $$экскурсия$$, 'noun', 'feminine', 'not_applicable', false),
    (70, $$help$$, $$помощь$$, $$помощь$$, 'noun', 'feminine', 'not_applicable', false),
    (71, $$hire$$, $$прокат$$, $$прокат$$, 'noun', 'masculine', 'not_applicable', false),
    (72, $$historic$$, $$исторический$$, $$исторический$$, 'adjective', 'not_applicable', 'not_applicable', false),
    (73, $$holidays (school)$$, $$каникулы$$, $$каникулы$$, 'noun', 'plural_only', 'not_applicable', false),
    (74, $$hospital$$, $$больница$$, $$больница$$, 'noun', 'feminine', 'not_applicable', false),
    (75, $$hotel$$, $$гостиница$$, $$гостиница$$, 'noun', 'feminine', 'not_applicable', false),
    (76, $$hotel (5*)$$, $$отель$$, $$отель$$, 'noun', 'masculine', 'not_applicable', false),
    (77, $$ice rink$$, $$каток$$, $$каток$$, 'noun', 'masculine', 'not_applicable', false),
    (78, $$information office$$, $$справочное бюро$$, $$справочное бюро$$, 'noun', 'neuter', 'not_applicable', false),
    (79, $$journey (short), trip$$, $$поездка$$, $$поездка$$, 'noun', 'feminine', 'not_applicable', false),
    (80, $$key$$, $$ключ$$, $$ключ$$, 'noun', 'masculine', 'not_applicable', false),
    (81, $$lake$$, $$озеро$$, $$озеро$$, 'noun', 'neuter', 'not_applicable', false),
    (82, $$library$$, $$библиотека$$, $$библиотека$$, 'noun', 'feminine', 'not_applicable', false),
    (83, $$lift$$, $$лифт$$, $$лифт$$, 'noun', 'masculine', 'not_applicable', false),
    (84, $$local area$$, $$местность$$, $$местность$$, 'noun', 'feminine', 'not_applicable', false),
    (85, $$luggage$$, $$багаж$$, $$багаж$$, 'noun', 'masculine', 'not_applicable', false),
    (86, $$map$$, $$карта$$, $$карта$$, 'noun', 'feminine', 'not_applicable', false),
    (87, $$map (of town)$$, $$план (города)$$, $$план (города)$$, 'noun', 'masculine', 'not_applicable', false),
    (88, $$market$$, $$рынок$$, $$рынок$$, 'noun', 'masculine', 'not_applicable', false),
    (89, $$means of transport$$, $$вид транспорта$$, $$вид транспорта$$, 'noun', 'masculine', 'not_applicable', false),
    (90, $$microwave$$, $$микроволновка$$, $$микроволновка$$, 'noun', 'feminine', 'not_applicable', false),
    (91, $$monument$$, $$памятник$$, $$памятник$$, 'noun', 'masculine', 'not_applicable', false),
    (92, $$motorbike$$, $$мотоцикл$$, $$мотоцикл$$, 'noun', 'masculine', 'not_applicable', false),
    (93, $$mountain$$, $$гора$$, $$гора$$, 'noun', 'feminine', 'not_applicable', false),
    (94, $$museum$$, $$музей$$, $$музей$$, 'noun', 'masculine', 'not_applicable', false),
    (95, $$newspaper stall$$, $$газетный киоск$$, $$газетный киоск$$, 'noun', 'masculine', 'not_applicable', false),
    (96, $$night club$$, $$ночной клуб$$, $$ночной клуб$$, 'noun', 'masculine', 'not_applicable', false),
    (97, $$occupied/taken$$, $$занято$$, $$занято$$, 'adverb', 'not_applicable', 'not_applicable', false),
    (98, $$office$$, $$офис$$, $$офис$$, 'noun', 'masculine', 'not_applicable', false),
    (99, $$on foot$$, $$пешком$$, $$пешком$$, 'adverb', 'not_applicable', 'not_applicable', false),
    (100, $$on the left$$, $$слева$$, $$слева$$, 'adverb', 'not_applicable', 'not_applicable', false),
    (101, $$on the right$$, $$справа$$, $$справа$$, 'adverb', 'not_applicable', 'not_applicable', false),
    (102, $$open$$, $$открыто$$, $$открыто$$, 'adverb', 'not_applicable', 'not_applicable', false),
    (103, $$palace$$, $$дворец$$, $$дворец$$, 'noun', 'masculine', 'not_applicable', false),
    (104, $$paper$$, $$бумага$$, $$бумага$$, 'noun', 'feminine', 'not_applicable', false),
    (105, $$park$$, $$парк$$, $$парк$$, 'noun', 'masculine', 'not_applicable', false),
    (106, $$passenger$$, $$пассажир$$, $$пассажир$$, 'noun', 'masculine', 'not_applicable', false),
    (107, $$passport$$, $$паспорт$$, $$паспорт$$, 'noun', 'masculine', 'not_applicable', false),
    (108, $$passport control$$, $$паспортный контроль$$, $$паспортный контроль$$, 'noun', 'masculine', 'not_applicable', false),
    (109, $$petrol$$, $$бензин$$, $$бензин$$, 'noun', 'masculine', 'not_applicable', false),
    (110, $$place$$, $$место$$, $$место$$, 'noun', 'neuter', 'not_applicable', false),
    (111, $$plane$$, $$самолёт$$, $$самолёт$$, 'noun', 'masculine', 'not_applicable', false),
    (112, $$platform$$, $$платформа$$, $$платформа$$, 'noun', 'feminine', 'not_applicable', false),
    (113, $$policeman$$, $$полицейский / милиционер$$, $$полицейский; милиционер$$, 'noun', 'masculine', 'not_applicable', false),
    (114, $$port$$, $$порт$$, $$порт$$, 'noun', 'masculine', 'not_applicable', false),
    (115, $$post office$$, $$почта$$, $$почта$$, 'noun', 'feminine', 'not_applicable', false),
    (116, $$postcard$$, $$открытка$$, $$открытка$$, 'noun', 'feminine', 'not_applicable', false),
    (117, $$poster$$, $$плакат$$, $$плакат$$, 'noun', 'masculine', 'not_applicable', false),
    (118, $$priority$$, $$приоритет$$, $$приоритет$$, 'noun', 'masculine', 'not_applicable', false),
    (119, $$problem$$, $$проблема$$, $$проблема$$, 'noun', 'feminine', 'not_applicable', false),
    (120, $$public$$, $$общественный$$, $$общественный$$, 'adjective', 'not_applicable', 'not_applicable', false),
    (121, $$public transport$$, $$городской транспорт$$, $$городской транспорт$$, 'noun', 'masculine', 'not_applicable', false),
    (122, $$radio$$, $$радио$$, $$радио$$, 'noun', 'neuter', 'not_applicable', false),
    (123, $$railway$$, $$железная дорога$$, $$железная дорога$$, 'noun', 'feminine', 'not_applicable', false),
    (124, $$railway carriage$$, $$вагон$$, $$вагон$$, 'noun', 'masculine', 'not_applicable', false),
    (125, $$recommendation$$, $$рекомендация$$, $$рекомендация$$, 'noun', 'feminine', 'not_applicable', false),
    (126, $$region, area$$, $$регион$$, $$регион$$, 'noun', 'masculine', 'not_applicable', false),
    (127, $$region, district$$, $$район$$, $$район$$, 'noun', 'masculine', 'not_applicable', false),
    (128, $$resort$$, $$курорт$$, $$курорт$$, 'noun', 'masculine', 'not_applicable', false),
    (129, $$return ticket$$, $$обратный билет$$, $$обратный билет$$, 'noun', 'masculine', 'not_applicable', false),
    (130, $$river$$, $$река$$, $$река$$, 'noun', 'feminine', 'not_applicable', false),
    (131, $$road$$, $$дорога$$, $$дорога$$, 'noun', 'feminine', 'not_applicable', false),
    (132, $$room$$, $$комната$$, $$комната$$, 'noun', 'feminine', 'not_applicable', false),
    (133, $$room (in hotel)$$, $$номер$$, $$номер$$, 'noun', 'masculine', 'not_applicable', false),
    (134, $$Russian doll$$, $$матрёшка$$, $$матрёшка$$, 'noun', 'feminine', 'not_applicable', false),
    (135, $$sea$$, $$море$$, $$море$$, 'noun', 'neuter', 'not_applicable', false),
    (136, $$season$$, $$сезон / время года$$, $$сезон, время года$$, 'noun', 'unknown', 'not_applicable', false),
    (137, $$shop$$, $$магазин$$, $$магазин$$, 'noun', 'masculine', 'not_applicable', false),
    (138, $$shopping$$, $$покупки$$, $$покупки$$, 'noun', 'plural_only', 'not_applicable', false),
    (139, $$shopping centre$$, $$торговый центр$$, $$торговый центр$$, 'noun', 'masculine', 'not_applicable', false),
    (140, $$show$$, $$шоу$$, $$шоу$$, 'noun', 'neuter', 'not_applicable', false),
    (141, $$shower$$, $$душ$$, $$душ$$, 'noun', 'masculine', 'not_applicable', false),
    (142, $$sight, tourist attraction, place to see$$, $$достопримечательность$$, $$достопримечательность f$$, 'noun', 'feminine', 'not_applicable', false),
    (143, $$single ticket$$, $$билет в одну сторону$$, $$билет в одну сторону$$, 'noun', 'masculine', 'not_applicable', false),
    (144, $$snack bar$$, $$буфет$$, $$буфет$$, 'noun', 'masculine', 'not_applicable', false),
    (145, $$snack bar, buffet (on a train)$$, $$вагон-ресторан$$, $$вагон-ресторан$$, 'noun', 'masculine', 'not_applicable', false),
    (146, $$souvenir$$, $$сувенир$$, $$сувенир$$, 'noun', 'masculine', 'not_applicable', false),
    (147, $$sports centre$$, $$спортивный центр$$, $$спортивный центр$$, 'noun', 'masculine', 'not_applicable', false),
    (148, $$square (in town)$$, $$площадь$$, $$площадь$$, 'noun', 'feminine', 'not_applicable', false),
    (149, $$stadium$$, $$стадион$$, $$стадион$$, 'noun', 'masculine', 'not_applicable', false),
    (150, $$station (mainline railway)$$, $$вокзал$$, $$вокзал$$, 'noun', 'masculine', 'not_applicable', false),
    (151, $$station (metro)$$, $$станция$$, $$станция$$, 'noun', 'feminine', 'not_applicable', false),
    (152, $$stop (bus, tram etc)$$, $$остановка$$, $$остановка$$, 'noun', 'feminine', 'not_applicable', false),
    (153, $$street$$, $$улица$$, $$улица$$, 'noun', 'feminine', 'not_applicable', false),
    (154, $$suburb; outskirts of town$$, $$пригород$$, $$пригород$$, 'noun', 'masculine', 'not_applicable', false),
    (155, $$suitcase$$, $$чемодан$$, $$чемодан$$, 'noun', 'masculine', 'not_applicable', false),
    (156, $$supermarket$$, $$супермаркет$$, $$супермаркет$$, 'noun', 'masculine', 'not_applicable', false),
    (157, $$supermarket$$, $$универсам$$, $$универсам$$, 'noun', 'masculine', 'not_applicable', false),
    (158, $$swimming pool$$, $$бассейн$$, $$бассейн$$, 'noun', 'masculine', 'not_applicable', false),
    (159, $$taxi$$, $$такси$$, $$такси$$, 'noun', 'neuter', 'not_applicable', false),
    (160, $$teenager$$, $$тинейджер$$, $$тинейджер$$, 'noun', 'masculine', 'not_applicable', false),
    (161, $$television set$$, $$телевизор$$, $$телевизор$$, 'noun', 'masculine', 'not_applicable', false),
    (162, $$tennis court$$, $$теннисный корт$$, $$теннисный корт$$, 'noun', 'masculine', 'not_applicable', false),
    (163, $$tent$$, $$палатка$$, $$палатка$$, 'noun', 'feminine', 'not_applicable', false),
    (164, $$theatre$$, $$театр$$, $$театр$$, 'noun', 'masculine', 'not_applicable', false),
    (165, $$ticket$$, $$билет$$, $$билет$$, 'noun', 'masculine', 'not_applicable', false),
    (166, $$ticket office$$, $$билетная касса$$, $$билетная касса$$, 'noun', 'feminine', 'not_applicable', false),
    (167, $$ticket; tram, bus or metro ticket$$, $$билет; билет на трамвай, автобус, метро$$, $$билет; билет на трамвай, автобус, метро$$, 'noun', 'masculine', 'not_applicable', false),
    (168, $$till; cash desk$$, $$касса$$, $$касса$$, 'noun', 'feminine', 'not_applicable', false),
    (169, $$to photograph$$, $$фотографировать / сфотографировать$$, $$фотографировать/с-$$, 'verb', 'not_applicable', 'both', false),
    (170, $$toilets$$, $$туалеты$$, $$туалеты$$, 'noun', 'plural_only', 'not_applicable', false),
    (171, $$token (metro)$$, $$жетон$$, $$жетон$$, 'noun', 'masculine', 'not_applicable', false),
    (172, $$tour$$, $$тур$$, $$тур$$, 'noun', 'masculine', 'not_applicable', false),
    (173, $$tourism$$, $$туризм$$, $$туризм$$, 'noun', 'masculine', 'not_applicable', false),
    (174, $$tourist$$, $$турист$$, $$турист$$, 'noun', 'masculine', 'not_applicable', false),
    (175, $$tourist (adjective)$$, $$туристический$$, $$туристический$$, 'adjective', 'not_applicable', 'not_applicable', false),
    (176, $$tourist information office$$, $$туристическое бюро$$, $$туристическое бюро$$, 'noun', 'neuter', 'not_applicable', false),
    (177, $$town$$, $$город$$, $$город$$, 'noun', 'masculine', 'not_applicable', false),
    (178, $$town centre$$, $$центр города$$, $$центр города$$, 'noun', 'masculine', 'not_applicable', false),
    (179, $$train$$, $$поезд$$, $$поезд$$, 'noun', 'masculine', 'not_applicable', false),
    (180, $$tram$$, $$трамвай$$, $$трамвай$$, 'noun', 'masculine', 'not_applicable', false),
    (181, $$travel agency$$, $$турагентство$$, $$турагентство$$, 'noun', 'neuter', 'not_applicable', false),
    (182, $$trolleybus$$, $$троллейбус$$, $$троллейбус$$, 'noun', 'masculine', 'not_applicable', false),
    (183, $$underground railway$$, $$метро$$, $$метро$$, 'noun', 'neuter', 'not_applicable', false),
    (184, $$underground station$$, $$станция метро$$, $$станция метро$$, 'noun', 'feminine', 'not_applicable', false),
    (185, $$vacation$$, $$отпуск$$, $$отпуск$$, 'noun', 'masculine', 'not_applicable', false),
    (186, $$view (over)$$, $$вид (на)$$, $$вид (на)$$, 'noun', 'masculine', 'not_applicable', false),
    (187, $$village$$, $$деревня$$, $$деревня$$, 'noun', 'feminine', 'not_applicable', false),
    (188, $$way out/exit$$, $$выход$$, $$выход$$, 'noun', 'masculine', 'not_applicable', false),
    (189, $$welcome$$, $$добро пожаловать$$, $$добро пожаловать$$, 'phrase', 'not_applicable', 'not_applicable', false),
    (190, $$window$$, $$окно$$, $$окно$$, 'noun', 'neuter', 'not_applicable', false),
    (191, $$winter holidays$$, $$зимние каникулы$$, $$зимние каникулы$$, 'noun', 'plural_only', 'not_applicable', false),
    (192, $$yard, courtyard$$, $$двор$$, $$двор$$, 'noun', 'masculine', 'not_applicable', false),
    (193, $$youth hostel$$, $$молодёжная гостиница$$, $$молодёжная гостиница$$, 'noun', 'feminine', 'not_applicable', false),
    (194, $$zoo$$, $$зоопарк$$, $$зоопарк$$, 'noun', 'masculine', 'not_applicable', false)
),
prepared_items as (
  select
    raw_items.position,
    raw_items.english,
    raw_items.russian,
    raw_items.spec_russian,
    raw_items.part_of_speech,
    raw_items.gender,
    raw_items.aspect,
    raw_items.is_reflexive,
    case
      when raw_items.part_of_speech = 'phrase' or raw_items.russian ~ '\s' then 'phrase'
      else 'word'
    end as item_type,
    (
      'local-area-holiday-and-travel-foundation:item-' ||
      lpad(raw_items.position::text, 3, '0')
    ) as import_key,
    regexp_replace(
      lower(raw_items.english),
      '[^a-z0-9]+',
      '-',
      'g'
    ) as canonical_key
  from raw_items
),
upserted_items as (
  insert into public.vocabulary_items (
    vocabulary_set_id,
    canonical_key,
    russian,
    english,
    item_type,
    source_type,
    priority,
    part_of_speech,
    gender,
    productive_receptive,
    tier,
    theme_key,
    topic_key,
    category_key,
    aspect,
    is_reflexive,
    source_key,
    source_version,
    source_section_ref,
    import_key,
    position,
    spec_russian,
    notes
  )
  select
    upserted_list.vocabulary_set_id,
    trim(both '-' from prepared_items.canonical_key),
    prepared_items.russian,
    prepared_items.english,
    prepared_items.item_type,
    'spec_required',
    'core',
    prepared_items.part_of_speech,
    prepared_items.gender,
    'unknown',
    'foundation',
    'local_area_holiday_travel',
    'local_area_holiday_travel',
    'local_area_holiday_travel',
    prepared_items.aspect,
    prepared_items.is_reflexive,
    'pearson_edexcel_gcse_russian_1ru0',
    '1RU0',
    'Section 2: Topic-specific vocabulary / Local area, holiday and travel / Foundation tier',
    prepared_items.import_key,
    prepared_items.position,
    prepared_items.spec_russian,
    null
  from prepared_items
  cross join upserted_list
  on conflict (source_key, import_key)
  where source_key is not null and import_key is not null
  do update
  set
    vocabulary_set_id = excluded.vocabulary_set_id,
    canonical_key = excluded.canonical_key,
    russian = excluded.russian,
    english = excluded.english,
    item_type = excluded.item_type,
    source_type = excluded.source_type,
    priority = excluded.priority,
    part_of_speech = excluded.part_of_speech,
    gender = excluded.gender,
    productive_receptive = excluded.productive_receptive,
    tier = excluded.tier,
    theme_key = excluded.theme_key,
    topic_key = excluded.topic_key,
    category_key = excluded.category_key,
    aspect = excluded.aspect,
    is_reflexive = excluded.is_reflexive,
    source_version = excluded.source_version,
    source_section_ref = excluded.source_section_ref,
    position = excluded.position,
    spec_russian = excluded.spec_russian,
    notes = excluded.notes,
    updated_at = now()
  returning id, import_key, position
)
insert into public.vocabulary_list_items (
  vocabulary_list_id,
  vocabulary_item_id,
  position,
  productive_receptive_override,
  tier_override,
  source_section_ref,
  import_key
)
select
  upserted_list.id,
  upserted_items.id,
  upserted_items.position,
  null,
  'foundation',
  'Section 2: Topic-specific vocabulary / Local area, holiday and travel / Foundation tier',
  upserted_items.import_key
from upserted_items
cross join upserted_list
on conflict (vocabulary_list_id, import_key)
where import_key is not null
do update
set
  vocabulary_item_id = excluded.vocabulary_item_id,
  position = excluded.position,
  productive_receptive_override = excluded.productive_receptive_override,
  tier_override = excluded.tier_override,
  source_section_ref = excluded.source_section_ref;

commit;
