begin;

with grammar_set_rows (
  slug,
  title,
  description,
  topic_key,
  tier,
  sort_order,
  import_key
) as (
  values
    ('nouns', 'Nouns', 'Noun gender, number, case, irregular forms, and adjectives used as nouns from Appendix 2.', 'nouns', 'both', 10, 'appendix-2:nouns'),
    ('adjectives', 'Adjectives', 'Adjective forms, comparison, negation, and superlatives from Appendix 2.', 'adjectives', 'both', 20, 'appendix-2:adjectives'),
    ('adverbs', 'Adverbs', 'Adverb formation and comparative adverbs from Appendix 2.', 'adverbs', 'both', 30, 'appendix-2:adverbs'),
    ('quantifiers-intensifiers', 'Quantifiers and intensifiers', 'Core quantifiers and intensifiers from Appendix 2.', 'quantifiers_intensifiers', 'foundation', 40, 'appendix-2:quantifiers-intensifiers'),
    ('pronouns-personal', 'Personal pronouns', 'Personal pronoun case requirements from Appendix 2.', 'pronouns_personal', 'both', 50, 'appendix-2:pronouns-personal'),
    ('pronouns-other', 'Other pronouns', 'Demonstrative, interrogative, relative, reciprocal, and indefinite pronouns from Appendix 2.', 'pronouns_other', 'both', 60, 'appendix-2:pronouns-other'),
    ('possessives', 'Possessives', 'Possessive pronouns and свой from Appendix 2.', 'possessives', 'both', 70, 'appendix-2:possessives'),
    ('verbs', 'Verbs', 'Tenses, infinitives, reflexives, imperatives, motion verbs, and participles from Appendix 2.', 'verbs', 'both', 80, 'appendix-2:verbs'),
    ('impersonal-constructions', 'Impersonal constructions', 'Нравиться, хотеться, feeling constructions, надо/нужно, and можно from Appendix 2.', 'impersonal_constructions', 'both', 90, 'appendix-2:impersonal-constructions'),
    ('numbers-and-quantity', 'Numbers and quantity', 'Cardinal numbers, ordinals, approximation, and quantity expressions from Appendix 2.', 'numbers_and_quantity', 'both', 100, 'appendix-2:numbers-and-quantity'),
    ('prepositions', 'Prepositions', 'Foundation and Higher preposition requirements from Appendix 2.', 'prepositions', 'both', 110, 'appendix-2:prepositions'),
    ('conjunctions', 'Conjunctions', 'Foundation and Higher conjunction requirements from Appendix 2.', 'conjunctions', 'both', 120, 'appendix-2:conjunctions'),
    ('times-and-dates', 'Times and dates', 'Time, date, duration, and frequency structures from Appendix 2.', 'times_and_dates', 'both', 130, 'appendix-2:times-and-dates'),
    ('negation', 'Negation', 'Не, нет + genitive, ни- forms, and ни...ни... from Appendix 2.', 'negation', 'both', 140, 'appendix-2:negation')
)
insert into public.grammar_sets (
  slug,
  title,
  description,
  theme_key,
  topic_key,
  tier,
  sort_order,
  is_published,
  is_trial_visible,
  requires_paid_access,
  available_in_volna,
  source_key,
  source_version,
  import_key
)
select
  slug,
  title,
  description,
  'grammar',
  topic_key,
  tier,
  sort_order,
  true,
  false,
  true,
  true,
  'edexcel_gcse_russian_appendix_2',
  'Appendix 2: Grammar list',
  import_key
from grammar_set_rows
on conflict (slug) do update set
  title = excluded.title,
  description = excluded.description,
  theme_key = excluded.theme_key,
  topic_key = excluded.topic_key,
  tier = excluded.tier,
  sort_order = excluded.sort_order,
  is_published = excluded.is_published,
  available_in_volna = excluded.available_in_volna,
  source_key = excluded.source_key,
  source_version = excluded.source_version,
  import_key = excluded.import_key,
  updated_at = now();

with grammar_point_rows (
  set_slug,
  slug,
  title,
  short_description,
  tier,
  knowledge_requirement,
  category_key,
  sort_order,
  import_key
) as (
  values
    ('nouns', 'nouns-word-class', 'Nouns as a word class', 'Recognise and use Russian nouns.', 'foundation', 'productive', 'nouns', 10, 'foundation:nouns:nouns-word-class'),
    ('nouns', 'noun-gender', 'Noun gender', 'Understand masculine, feminine, and neuter noun gender.', 'foundation', 'productive', 'nouns', 20, 'foundation:nouns:gender'),
    ('nouns', 'noun-number', 'Noun number', 'Understand singular and plural noun number.', 'foundation', 'productive', 'nouns', 30, 'foundation:nouns:number'),
    ('nouns', 'noun-case-system', 'Noun cases', 'Understand that nouns change form by case.', 'foundation', 'productive', 'nouns', 40, 'foundation:nouns:case-system'),
    ('nouns', 'common-irregular-plurals', 'Common irregular noun plurals', 'Use common irregular forms, for example друзья, дома.', 'foundation', 'productive', 'nouns', 50, 'foundation:nouns:common-irregular-plurals'),
    ('nouns', 'adjectives-used-as-nouns', 'Adjectives used as nouns', 'Use adjectives as nouns, for example столовая, русский, мороженое.', 'foundation', 'productive', 'nouns', 60, 'foundation:nouns:adjectives-used-as-nouns'),
    ('adjectives', 'long-forms-singular-cases', 'Long adjective forms: singular', 'Use long-form adjectives in singular cases.', 'foundation', 'productive', 'adjectives', 10, 'foundation:adjectives:long-forms-singular-cases'),
    ('adjectives', 'long-forms-plural-cases', 'Long adjective forms: plural', 'Use long-form adjectives in plural cases.', 'foundation', 'productive', 'adjectives', 20, 'foundation:adjectives:long-forms-plural-cases'),
    ('adjectives', 'negative-prefix-ne', 'Не- with adjectives', 'Use adjectives prefixed with не-.', 'foundation', 'productive', 'adjectives', 30, 'foundation:adjectives:negative-prefix-ne'),
    ('adjectives', 'simple-short-forms', 'Simple short-form adjectives', 'Use simple short forms, for example тепло, отлично.', 'foundation', 'productive', 'adjectives', 40, 'foundation:adjectives:simple-short-forms'),
    ('adjectives', 'comparatives-ee-receptive', 'Comparatives ending in -ее', 'Recognise comparatives ending in -ее, for example быстрее.', 'foundation', 'receptive', 'adjectives', 50, 'foundation:adjectives:comparatives-ee-receptive'),
    ('adjectives', 'special-short-comparatives', 'Special short-form comparatives', 'Use common special short-form comparatives, for example больше, меньше.', 'foundation', 'productive', 'adjectives', 60, 'foundation:adjectives:special-short-comparatives'),
    ('adjectives', 'comparative-than-chem', 'Чем after comparatives', 'Express "than" after a comparative using чем.', 'foundation', 'productive', 'adjectives', 70, 'foundation:adjectives:comparative-than-chem'),
    ('adjectives', 'bolee-comparatives-receptive', 'Более comparatives', 'Recognise comparatives formed with более.', 'foundation', 'receptive', 'adjectives', 80, 'foundation:adjectives:bolee-comparatives-receptive'),
    ('adjectives', 'samyi-superlatives-receptive', 'Самый superlatives', 'Recognise superlatives formed with самый.', 'foundation', 'receptive', 'adjectives', 90, 'foundation:adjectives:samyi-superlatives-receptive'),
    ('adjectives', 'common-short-forms-receptive', 'Common short-form adjectives', 'Recognise common short-form adjectives in singular and plural.', 'higher', 'receptive', 'adjectives', 100, 'higher:adjectives:common-short-forms-receptive'),
    ('adjectives', 'dolzhen-nuzhen-receptive', 'Должен and нужен', 'Recognise должен and нужен.', 'higher', 'receptive', 'adjectives', 110, 'higher:adjectives:dolzhen-nuzhen-receptive'),
    ('adjectives', 'comparatives-ee-productive', 'Comparatives ending in -ее', 'Use comparatives ending in -ее.', 'higher', 'productive', 'adjectives', 120, 'higher:adjectives:comparatives-ee-productive'),
    ('adjectives', 'bolee-comparatives-productive', 'Более comparatives', 'Use comparatives formed with более.', 'higher', 'productive', 'adjectives', 130, 'higher:adjectives:bolee-comparatives-productive'),
    ('adjectives', 'menee-comparatives-receptive', 'Менее comparatives', 'Recognise comparatives formed with менее.', 'higher', 'receptive', 'adjectives', 140, 'higher:adjectives:menee-comparatives-receptive'),
    ('adjectives', 'po-short-comparatives-receptive', 'По- with short-form comparatives', 'Recognise по- with short-form comparatives, for example побольше.', 'higher', 'receptive', 'adjectives', 150, 'higher:adjectives:po-short-comparatives-receptive'),
    ('adjectives', 'special-long-comparatives-nominative', 'Special long-form comparatives', 'Use common special long-form comparatives in nominative singular and plural, for example лучший, старший.', 'higher', 'productive', 'adjectives', 160, 'higher:adjectives:special-long-comparatives-nominative'),
    ('adjectives', 'comparative-than-genitive-receptive', 'Genitive after comparatives', 'Recognise "than" expressed with the genitive after comparatives, for example моложе брата.', 'higher', 'receptive', 'adjectives', 170, 'higher:adjectives:comparative-than-genitive-receptive'),
    ('adjectives', 'samyi-superlatives-nominative', 'Самый superlatives: nominative', 'Use superlatives with самый in nominative singular and plural.', 'higher', 'productive', 'adjectives', 180, 'higher:adjectives:samyi-superlatives-nominative'),
    ('adjectives', 'samyi-superlatives-other-cases-receptive', 'Самый superlatives: other cases', 'Recognise superlatives with самый in cases other than nominative.', 'higher', 'receptive', 'adjectives', 190, 'higher:adjectives:samyi-superlatives-other-cases-receptive'),
    ('adverbs', 'o-forms', 'Adverbs ending in -о', 'Use adverbs ending in -о, for example быстро.', 'foundation', 'productive', 'adverbs', 10, 'foundation:adverbs:o-forms'),
    ('adverbs', 'po-language-forms', 'По- language adverbs', 'Use forms such as по-русски and по-английски.', 'foundation', 'productive', 'adverbs', 20, 'foundation:adverbs:po-language-forms'),
    ('adverbs', 'comparative-forms-receptive', 'Comparative adverbs', 'Recognise comparative adverb forms.', 'foundation', 'receptive', 'adverbs', 30, 'foundation:adverbs:comparative-forms-receptive'),
    ('adverbs', 'comparative-forms-productive', 'Comparative adverbs', 'Use comparative adverb forms.', 'higher', 'productive', 'adverbs', 40, 'higher:adverbs:comparative-forms-productive'),
    ('adverbs', 'ski-forms-receptive', 'Adverbs ending in -ски', 'Recognise adverbs ending in -ски, for example практически.', 'higher', 'receptive', 'adverbs', 50, 'higher:adverbs:ski-forms-receptive'),
    ('adverbs', 'po-prefix-receptive', 'По- with adverbs', 'Recognise use of prefix по- with adverbs.', 'higher', 'receptive', 'adverbs', 60, 'higher:adverbs:po-prefix-receptive'),
    ('quantifiers-intensifiers', 'ochen', 'Очень', 'Use очень as a quantifier or intensifier.', 'foundation', 'productive', 'quantifiers_intensifiers', 10, 'foundation:quantifiers:ochen'),
    ('quantifiers-intensifiers', 'dovolno', 'Довольно', 'Use довольно as a quantifier or intensifier.', 'foundation', 'productive', 'quantifiers_intensifiers', 20, 'foundation:quantifiers:dovolno'),
    ('quantifiers-intensifiers', 'slishkom', 'Слишком', 'Use слишком as a quantifier or intensifier.', 'foundation', 'productive', 'quantifiers_intensifiers', 30, 'foundation:quantifiers:slishkom'),
    ('pronouns-personal', 'first-person-all-cases', 'First-person personal pronouns', 'Use I/me personal pronouns in all cases.', 'foundation', 'productive', 'pronouns_personal', 10, 'foundation:pronouns-personal:first-person-all-cases'),
    ('pronouns-personal', 'other-nominative-receptive', 'Other personal pronouns: nominative', 'Recognise other personal pronouns in the nominative.', 'foundation', 'receptive', 'pronouns_personal', 20, 'foundation:pronouns-personal:other-nominative-receptive'),
    ('pronouns-personal', 'other-accusative-receptive', 'Other personal pronouns: accusative', 'Recognise other personal pronouns in the accusative.', 'foundation', 'receptive', 'pronouns_personal', 30, 'foundation:pronouns-personal:other-accusative-receptive'),
    ('pronouns-personal', 'other-dative-receptive', 'Other personal pronouns: dative', 'Recognise other personal pronouns in the dative.', 'foundation', 'receptive', 'pronouns_personal', 40, 'foundation:pronouns-personal:other-dative-receptive'),
    ('pronouns-personal', 'i-he-she-they-all-cases', 'I, he, she, they in all cases', 'Use personal pronouns I, he, she, and they in all cases.', 'higher', 'productive', 'pronouns_personal', 50, 'higher:pronouns-personal:i-he-she-they-all-cases'),
    ('pronouns-personal', 'other-all-cases-receptive', 'Other personal pronouns in all cases', 'Recognise other personal pronouns in all cases.', 'higher', 'receptive', 'pronouns_personal', 60, 'higher:pronouns-personal:other-all-cases-receptive'),
    ('pronouns-other', 'etot-all-cases', 'Этот in all cases', 'Use этот in all cases, singular and relevant plural forms.', 'foundation', 'productive', 'pronouns_other', 10, 'foundation:pronouns-other:etot-all-cases'),
    ('pronouns-other', 'kto-all-cases', 'Кто in all cases', 'Use кто in all cases.', 'foundation', 'productive', 'pronouns_other', 20, 'foundation:pronouns-other:kto-all-cases'),
    ('pronouns-other', 'chto-all-cases', 'Что in all cases', 'Use что in all cases.', 'foundation', 'productive', 'pronouns_other', 30, 'foundation:pronouns-other:chto-all-cases'),
    ('pronouns-other', 'kakoi-all-cases', 'Какой in all cases', 'Use какой in all cases, singular and relevant plural forms.', 'foundation', 'productive', 'pronouns_other', 40, 'foundation:pronouns-other:kakoi-all-cases'),
    ('pronouns-other', 'kazhdyi-all-cases', 'Каждый in all cases', 'Use каждый in all cases, singular and relevant plural forms.', 'foundation', 'productive', 'pronouns_other', 50, 'foundation:pronouns-other:kazhdyi-all-cases'),
    ('pronouns-other', 'listed-pronouns-plural-receptive', 'Plural forms of listed pronouns', 'Recognise relevant plural forms of этот, какой, and каждый.', 'foundation', 'receptive', 'pronouns_other', 60, 'foundation:pronouns-other:listed-pronouns-plural-receptive'),
    ('pronouns-other', 'tot-all-cases-receptive', 'Тот in all cases', 'Recognise тот in all cases, singular and plural.', 'foundation', 'receptive', 'pronouns_other', 70, 'foundation:pronouns-other:tot-all-cases-receptive'),
    ('pronouns-other', 'takoi-all-cases-receptive', 'Такой in all cases', 'Recognise такой in all cases, singular and plural.', 'foundation', 'receptive', 'pronouns_other', 80, 'foundation:pronouns-other:takoi-all-cases-receptive'),
    ('pronouns-other', 'kotoryi-all-cases-receptive', 'Который in all cases', 'Recognise который in all cases, singular and plural.', 'foundation', 'receptive', 'pronouns_other', 90, 'foundation:pronouns-other:kotoryi-all-cases-receptive'),
    ('pronouns-other', 'ves-related-forms-receptive', 'Весь and related forms', 'Recognise весь and related forms in all cases, singular and plural.', 'foundation', 'receptive', 'pronouns_other', 100, 'foundation:pronouns-other:ves-related-forms-receptive'),
    ('pronouns-other', 'etot-kto-chto-kakoi-kazhdyi-all-cases', 'Этот, кто, что, какой, каждый: singular and plural', 'Use этот, кто, что, какой, and каждый in all cases, singular and plural.', 'higher', 'productive', 'pronouns_other', 110, 'higher:pronouns-other:etot-kto-chto-kakoi-kazhdyi-all-cases'),
    ('pronouns-other', 'tot-all-cases', 'Тот in all cases', 'Use тот in all cases.', 'higher', 'productive', 'pronouns_other', 120, 'higher:pronouns-other:tot-all-cases'),
    ('pronouns-other', 'takoi-all-cases', 'Такой in all cases', 'Use такой in all cases.', 'higher', 'productive', 'pronouns_other', 130, 'higher:pronouns-other:takoi-all-cases'),
    ('pronouns-other', 'kotoryi-simple-usage', 'Который in simple usage', 'Use который in simple phrases, for example друг, которого зовут Андрей.', 'higher', 'productive', 'pronouns_other', 140, 'higher:pronouns-other:kotoryi-simple-usage'),
    ('pronouns-other', 'nibud-to-receptive', '-нибудь and -то pronouns', 'Recognise common use of -нибудь and -то.', 'higher', 'receptive', 'pronouns_other', 150, 'higher:pronouns-other:nibud-to-receptive'),
    ('pronouns-other', 'drug-druga-receptive', 'Друг друга', 'Recognise друг друга and related reciprocal forms.', 'higher', 'receptive', 'pronouns_other', 160, 'higher:pronouns-other:drug-druga-receptive'),
    ('pronouns-other', 'vse-chto-to-chto-receptive', 'Всё, что and то, что', 'Recognise use of всё, что and то, что.', 'higher', 'receptive', 'pronouns_other', 170, 'higher:pronouns-other:vse-chto-to-chto-receptive'),
    ('possessives', 'nominative-singular', 'Possessives: nominative singular', 'Use possessives in nominative singular.', 'foundation', 'productive', 'possessives', 10, 'foundation:possessives:nominative-singular'),
    ('possessives', 'nominative-plural', 'Possessives: nominative plural', 'Use possessives in nominative plural.', 'foundation', 'productive', 'possessives', 20, 'foundation:possessives:nominative-plural'),
    ('possessives', 'ego-eyo-ikh', 'Его, её, их', 'Use его, её, and их as possessives.', 'foundation', 'productive', 'possessives', 30, 'foundation:possessives:ego-eyo-ikh'),
    ('possessives', 'all-cases-singular', 'Possessives: all cases singular', 'Use possessives in all cases, singular.', 'higher', 'productive', 'possessives', 40, 'higher:possessives:all-cases-singular'),
    ('possessives', 'all-cases-plural-receptive', 'Possessives: all cases plural', 'Recognise possessives in all cases, plural.', 'higher', 'receptive', 'possessives', 50, 'higher:possessives:all-cases-plural-receptive'),
    ('possessives', 'svoi-all-cases-receptive', 'Свой', 'Recognise свой in all cases, singular and plural.', 'higher', 'receptive', 'possessives', 60, 'higher:possessives:svoi-all-cases-receptive'),
    ('verbs', 'present-tense', 'Present tense', 'Use the present tense.', 'foundation', 'productive', 'verbs', 10, 'foundation:verbs:present-tense'),
    ('verbs', 'imperfective-past', 'Imperfective past tense', 'Use the imperfective past tense.', 'foundation', 'productive', 'verbs', 20, 'foundation:verbs:imperfective-past'),
    ('verbs', 'perfective-past-receptive', 'Perfective past tense', 'Recognise the perfective past tense.', 'foundation', 'receptive', 'verbs', 30, 'foundation:verbs:perfective-past-receptive'),
    ('verbs', 'imperfective-future', 'Imperfective future tense', 'Use the imperfective future tense.', 'foundation', 'productive', 'verbs', 40, 'foundation:verbs:imperfective-future'),
    ('verbs', 'infinitives', 'Infinitives', 'Recognise and use infinitives.', 'foundation', 'productive', 'verbs', 50, 'foundation:verbs:infinitives'),
    ('verbs', 'reflexive-verbs', 'Reflexive verbs', 'Use reflexive verbs.', 'foundation', 'productive', 'verbs', 60, 'foundation:verbs:reflexive-verbs'),
    ('verbs', 'classroom-imperatives', 'Common classroom imperatives', 'Use common imperatives дай/дайте and classroom commands only.', 'foundation', 'productive', 'verbs', 70, 'foundation:verbs:classroom-imperatives'),
    ('verbs', 'motion-khodit-idti-poiti', 'Ходить, идти, пойти', 'Use common forms of ходить, идти, and пойти.', 'foundation', 'productive', 'verbs', 80, 'foundation:verbs:motion-khodit-idti-poiti'),
    ('verbs', 'motion-ezdit-ekhat-poekhat', 'Ездить, ехать, поехать', 'Use common forms of ездить, ехать, and поехать.', 'foundation', 'productive', 'verbs', 90, 'foundation:verbs:motion-ezdit-ekhat-poekhat'),
    ('verbs', 'prefixed-motion-receptive', 'Prefixed verbs of motion', 'Recognise common prefixed verbs of motion, for example приходить/прийти, уезжать/уехать.', 'foundation', 'receptive', 'verbs', 100, 'foundation:verbs:prefixed-motion-receptive'),
    ('verbs', 'foundation-vocab-motion-verbs', 'Foundation vocabulary verbs of motion', 'Use other verbs of motion only as listed in Foundation vocabulary.', 'foundation', 'productive', 'verbs', 110, 'foundation:verbs:foundation-vocab-motion-verbs'),
    ('verbs', 'otkryt-zakryt', 'Открыт and закрыт', 'Use past passive participles открыт and закрыт only.', 'foundation', 'productive', 'verbs', 120, 'foundation:verbs:otkryt-zakryt'),
    ('verbs', 'perfective-past-productive', 'Perfective past tense', 'Use the perfective past tense.', 'higher', 'productive', 'verbs', 130, 'higher:verbs:perfective-past-productive'),
    ('verbs', 'perfective-future-first-person-singular', 'Perfective future: first person singular', 'Use the perfective future in first person singular.', 'higher', 'productive', 'verbs', 140, 'higher:verbs:perfective-future-first-person-singular'),
    ('verbs', 'perfective-future-other-persons-receptive', 'Perfective future: other persons', 'Recognise the perfective future in other persons.', 'higher', 'receptive', 'verbs', 150, 'higher:verbs:perfective-future-other-persons-receptive'),
    ('verbs', 'imperatives-second-person-singular', 'Second-person singular imperatives', 'Use second-person singular imperatives.', 'higher', 'productive', 'verbs', 160, 'higher:verbs:imperatives-second-person-singular'),
    ('verbs', 'imperatives-second-person-plural', 'Second-person plural imperatives', 'Use second-person plural imperatives.', 'higher', 'productive', 'verbs', 170, 'higher:verbs:imperatives-second-person-plural'),
    ('verbs', 'imperatives-first-person-plural-receptive', 'First-person plural imperatives', 'Recognise first-person plural imperatives.', 'higher', 'receptive', 'verbs', 180, 'higher:verbs:imperatives-first-person-plural-receptive'),
    ('verbs', 'third-person-plural-without-oni-receptive', 'Third person plural without они', 'Recognise third person plural verb forms used without они.', 'higher', 'receptive', 'verbs', 190, 'higher:verbs:third-person-plural-without-oni-receptive'),
    ('verbs', 'khotet-by-first-person-singular', 'Хотел/а бы', 'Use бы with хотеть in first person singular, for example хотел/а бы.', 'higher', 'productive', 'verbs', 200, 'higher:verbs:khotet-by-first-person-singular'),
    ('impersonal-constructions', 'nravitsya-present', 'Нравиться: present tense', 'Use нравиться in the present tense.', 'foundation', 'productive', 'impersonal_constructions', 10, 'foundation:impersonal:nravitsya-present'),
    ('impersonal-constructions', 'feelings-present', 'Feeling constructions: present tense', 'Use common present-tense feeling constructions, for example мне холодно, мне тепло.', 'foundation', 'productive', 'impersonal_constructions', 20, 'foundation:impersonal:feelings-present'),
    ('impersonal-constructions', 'nado-nuzhno-present', 'Надо / нужно: present tense', 'Use надо / нужно in the present tense.', 'foundation', 'productive', 'impersonal_constructions', 30, 'foundation:impersonal:nado-nuzhno-present'),
    ('impersonal-constructions', 'mozhno-present', 'Можно: present tense', 'Use можно in the present tense.', 'foundation', 'productive', 'impersonal_constructions', 40, 'foundation:impersonal:mozhno-present'),
    ('impersonal-constructions', 'nravitsya-all-tenses', 'Нравиться: all tenses', 'Use нравиться in all tenses.', 'higher', 'productive', 'impersonal_constructions', 50, 'higher:impersonal:nravitsya-all-tenses'),
    ('impersonal-constructions', 'khotetsya-present', 'Хотеться: present tense', 'Use хотеться in the present tense.', 'higher', 'productive', 'impersonal_constructions', 60, 'higher:impersonal:khotetsya-present'),
    ('impersonal-constructions', 'khotetsya-other-tenses-receptive', 'Хотеться: other tenses', 'Recognise хотеться in tenses other than present.', 'higher', 'receptive', 'impersonal_constructions', 70, 'higher:impersonal:khotetsya-other-tenses-receptive'),
    ('impersonal-constructions', 'feelings-all-tenses', 'Feeling constructions: all tenses', 'Use common feeling constructions in all tenses.', 'higher', 'productive', 'impersonal_constructions', 80, 'higher:impersonal:feelings-all-tenses'),
    ('impersonal-constructions', 'nado-nuzhno-all-tenses', 'Надо / нужно: all tenses', 'Use надо / нужно in all tenses.', 'higher', 'productive', 'impersonal_constructions', 90, 'higher:impersonal:nado-nuzhno-all-tenses'),
    ('impersonal-constructions', 'mozhno-all-tenses', 'Можно: all tenses', 'Use можно in all tenses.', 'higher', 'productive', 'impersonal_constructions', 100, 'higher:impersonal:mozhno-all-tenses'),
    ('numbers-and-quantity', 'cardinals-nominative', 'Cardinal numbers: nominative', 'Use cardinal numbers in the nominative.', 'foundation', 'productive', 'numbers_and_quantity', 10, 'foundation:numbers:cardinals-nominative'),
    ('numbers-and-quantity', 'cardinals-common-oblique-receptive', 'Cardinal numbers: common oblique cases', 'Recognise cardinal numbers in other cases for common uses.', 'foundation', 'receptive', 'numbers_and_quantity', 20, 'foundation:numbers:cardinals-common-oblique-receptive'),
    ('numbers-and-quantity', 'ordinals-dates-years-receptive', 'Ordinal numbers for dates and years', 'Recognise ordinal numbers for dates, including years.', 'foundation', 'receptive', 'numbers_and_quantity', 30, 'foundation:numbers:ordinals-dates-years-receptive'),
    ('numbers-and-quantity', 'ordinals-floors', 'Ordinal numbers for floors', 'Use ordinal numbers for floor numbers, for example на первом этаже.', 'foundation', 'productive', 'numbers_and_quantity', 40, 'foundation:numbers:ordinals-floors'),
    ('numbers-and-quantity', 'quantity-genitive-receptive', 'Quantity expressions with genitive', 'Recognise quantity expressions with the genitive, for example много, мало.', 'foundation', 'receptive', 'numbers_and_quantity', 50, 'foundation:numbers:quantity-genitive-receptive'),
    ('numbers-and-quantity', 'cardinals-all-cases', 'Cardinal numbers: all cases', 'Use cardinal numbers in all cases.', 'higher', 'productive', 'numbers_and_quantity', 60, 'higher:numbers:cardinals-all-cases'),
    ('numbers-and-quantity', 'approximation-inversion-receptive', 'Approximation inversion', 'Recognise inversion for approximation, for example минут десять.', 'higher', 'receptive', 'numbers_and_quantity', 70, 'higher:numbers:approximation-inversion-receptive'),
    ('numbers-and-quantity', 'ordinals-dates-years', 'Ordinal numbers for dates and years', 'Use ordinal numbers for dates, including years.', 'higher', 'productive', 'numbers_and_quantity', 80, 'higher:numbers:ordinals-dates-years'),
    ('numbers-and-quantity', 'quantity-genitive', 'Quantity expressions with genitive', 'Use quantity expressions with the genitive, for example много, мало.', 'higher', 'productive', 'numbers_and_quantity', 90, 'higher:numbers:quantity-genitive'),
    ('prepositions', 'foundation-vocabulary', 'Foundation vocabulary prepositions', 'Use prepositions listed in Foundation-tier vocabulary.', 'foundation', 'productive', 'prepositions', 10, 'foundation:prepositions:foundation-vocabulary'),
    ('prepositions', 'higher-vocabulary-receptive', 'Higher vocabulary prepositions', 'Recognise a wider range of prepositions listed in Higher-tier vocabulary.', 'higher', 'receptive', 'prepositions', 20, 'higher:prepositions:higher-vocabulary-receptive'),
    ('conjunctions', 'foundation-vocabulary', 'Foundation vocabulary conjunctions', 'Use conjunctions listed in Foundation-tier vocabulary.', 'foundation', 'productive', 'conjunctions', 10, 'foundation:conjunctions:foundation-vocabulary'),
    ('conjunctions', 'higher-vocabulary', 'Higher vocabulary conjunctions', 'Use conjunctions listed in Higher-tier vocabulary.', 'higher', 'productive', 'conjunctions', 20, 'higher:conjunctions:higher-vocabulary'),
    ('times-and-dates', 'twenty-four-hour-clock-receptive', '24-hour clock times', 'Recognise times using 24-hour clock format, for example 8.30, 19.25.', 'foundation', 'receptive', 'times_and_dates', 10, 'foundation:times-dates:twenty-four-hour-clock-receptive'),
    ('times-and-dates', 'days-months-receptive', 'Days and months', 'Recognise days and months.', 'foundation', 'receptive', 'times_and_dates', 20, 'foundation:times-dates:days-months-receptive'),
    ('times-and-dates', 'personal-date-birth', 'Personal date of birth', 'Give a personal date of birth.', 'foundation', 'productive', 'times_and_dates', 30, 'foundation:times-dates:personal-date-birth'),
    ('times-and-dates', 'personal-year-birth', 'Personal year of birth', 'Give a personal year of birth.', 'foundation', 'productive', 'times_and_dates', 40, 'foundation:times-dates:personal-year-birth'),
    ('times-and-dates', 'other-dates-years-receptive', 'Other dates and years', 'Recognise other dates and years.', 'foundation', 'receptive', 'times_and_dates', 50, 'foundation:times-dates:other-dates-years-receptive'),
    ('times-and-dates', 'time-structures-receptive', 'Time structures with and without prepositions', 'Recognise time structures such as утром, по субботам, в среду.', 'foundation', 'receptive', 'times_and_dates', 60, 'foundation:times-dates:time-structures-receptive'),
    ('times-and-dates', 'duration', 'Duration expressions', 'Use duration expressions, for example пять дней, на неделю.', 'foundation', 'productive', 'times_and_dates', 70, 'foundation:times-dates:duration'),
    ('times-and-dates', 'frequency-receptive', 'Frequency expressions', 'Recognise frequency expressions, for example два раза в неделю.', 'foundation', 'receptive', 'times_and_dates', 80, 'foundation:times-dates:frequency-receptive'),
    ('times-and-dates', 'twenty-four-hour-clock', '24-hour clock times', 'Use times in 24-hour clock format.', 'higher', 'productive', 'times_and_dates', 90, 'higher:times-dates:twenty-four-hour-clock'),
    ('times-and-dates', 'twelve-hour-clock-receptive', '12-hour clock times', 'Recognise 12-hour clock expressions, for example полшестого, без четверти.', 'higher', 'receptive', 'times_and_dates', 100, 'higher:times-dates:twelve-hour-clock-receptive'),
    ('times-and-dates', 'other-dates-years', 'Other dates and years', 'Use other dates and years.', 'higher', 'productive', 'times_and_dates', 110, 'higher:times-dates:other-dates-years'),
    ('times-and-dates', 'time-structures', 'Time structures with and without prepositions', 'Use time structures such as утром, по субботам, в среду.', 'higher', 'productive', 'times_and_dates', 120, 'higher:times-dates:time-structures'),
    ('times-and-dates', 'duration-higher', 'Duration expressions', 'Use duration expressions, for example пять дней, на неделю.', 'higher', 'productive', 'times_and_dates', 130, 'higher:times-dates:duration'),
    ('times-and-dates', 'frequency', 'Frequency expressions', 'Use frequency expressions, for example два раза в неделю.', 'higher', 'productive', 'times_and_dates', 140, 'higher:times-dates:frequency'),
    ('negation', 'simple-ne', 'Simple negation with не', 'Use simple negation with не.', 'foundation', 'productive', 'negation', 10, 'foundation:negation:simple-ne'),
    ('negation', 'net-genitive-present', 'Нет + genitive: present tense', 'Use нет + genitive in the present tense.', 'foundation', 'productive', 'negation', 20, 'foundation:negation:net-genitive-present'),
    ('negation', 'net-genitive-other-tenses-receptive', 'Нет + genitive: other tenses', 'Recognise нет + genitive in tenses other than present.', 'foundation', 'receptive', 'negation', 30, 'foundation:negation:net-genitive-other-tenses-receptive'),
    ('negation', 'ni-prefix-without-prepositions-receptive', 'Negative prefix ни- without prepositions', 'Recognise negative prefix ни- in case forms without prepositions, for example никто, никогда.', 'foundation', 'receptive', 'negation', 40, 'foundation:negation:ni-prefix-without-prepositions-receptive'),
    ('negation', 'net-genitive-all-tenses', 'Нет + genitive: all tenses', 'Use нет + genitive in all tenses.', 'higher', 'productive', 'negation', 50, 'higher:negation:net-genitive-all-tenses'),
    ('negation', 'ni-prefix-with-prepositions-receptive', 'Negative prefix ни- with prepositions', 'Recognise negative prefix ни- with prepositions, for example ни с кем.', 'higher', 'receptive', 'negation', 60, 'higher:negation:ni-prefix-with-prepositions-receptive'),
    ('negation', 'ni-ni-receptive', 'Ни... ни...', 'Recognise ни... ни... constructions.', 'higher', 'receptive', 'negation', 70, 'higher:negation:ni-ni-receptive')
)
insert into public.grammar_points (
  grammar_set_id,
  slug,
  title,
  short_description,
  full_explanation,
  spec_reference,
  category_key,
  tier,
  knowledge_requirement,
  sort_order,
  is_published,
  source_key,
  source_version,
  import_key
)
select
  sets.id,
  rows.slug,
  rows.title,
  rows.short_description,
  null,
  'Appendix 2: Grammar list',
  rows.category_key,
  rows.tier,
  rows.knowledge_requirement,
  rows.sort_order,
  true,
  'edexcel_gcse_russian_appendix_2',
  'Appendix 2: Grammar list',
  rows.import_key
from grammar_point_rows rows
join public.grammar_sets sets
  on sets.slug = rows.set_slug
on conflict (source_key, import_key)
  where source_key is not null and import_key is not null
do update set
  grammar_set_id = excluded.grammar_set_id,
  slug = excluded.slug,
  title = excluded.title,
  short_description = excluded.short_description,
  spec_reference = excluded.spec_reference,
  category_key = excluded.category_key,
  tier = excluded.tier,
  knowledge_requirement = excluded.knowledge_requirement,
  sort_order = excluded.sort_order,
  is_published = excluded.is_published,
  source_version = excluded.source_version,
  updated_at = now();

commit;
