begin;

insert into public.vocabulary_import_sources (
  source_key,
  title,
  source_version,
  publisher,
  notes
)
values (
  'pearson_edexcel_gcse_russian_1ru0',
  'Pearson Edexcel GCSE Russian vocabulary specification',
  '1RU0',
  'Pearson Edexcel',
  'Imported GCSE Russian specification vocabulary. Initial test import: Section 1, High-frequency language, Common verbs.'
)
on conflict (source_key) do update
set
  title = excluded.title,
  source_version = excluded.source_version,
  publisher = excluded.publisher,
  notes = excluded.notes,
  updated_at = now();

with upserted_set as (
  insert into public.vocabulary_sets (
    slug,
    title,
    description,
    theme_key,
    topic_key,
    tier,
    list_mode,
    set_type,
    default_display_variant,
    is_published,
    sort_order,
    source_key,
    source_version,
    import_key
  )
  values (
    'high-frequency-language-common-verbs',
    'Common verbs',
    'Spec-required high-frequency GCSE Russian verbs from Section 1: High-frequency language.',
    'high_frequency_language',
    'common_verbs',
    'both',
    'spec_only',
    'specification',
    'single_column',
    true,
    10,
    'pearson_edexcel_gcse_russian_1ru0',
    '1RU0',
    'section-1:high-frequency-language:common-verbs'
  )
  on conflict (source_key, import_key)
  where source_key is not null and import_key is not null
  do update
  set
    slug = excluded.slug,
    title = excluded.title,
    description = excluded.description,
    theme_key = excluded.theme_key,
    topic_key = excluded.topic_key,
    tier = excluded.tier,
    list_mode = excluded.list_mode,
    set_type = excluded.set_type,
    default_display_variant = excluded.default_display_variant,
    is_published = excluded.is_published,
    sort_order = excluded.sort_order,
    source_version = excluded.source_version,
    updated_at = now()
  returning id
),
upserted_list as (
  insert into public.vocabulary_lists (
    vocabulary_set_id,
    slug,
    title,
    description,
    theme_key,
    topic_key,
    category_key,
    tier,
    list_mode,
    default_display_variant,
    is_published,
    sort_order,
    source_key,
    source_version,
    source_section_ref,
    import_key
  )
  select
    id,
    'common-verbs',
    'Common verbs',
    'Spec-required high-frequency GCSE Russian common verbs.',
    'high_frequency_language',
    'common_verbs',
    'common_verbs',
    'both',
    'spec_only',
    'single_column',
    true,
    10,
    'pearson_edexcel_gcse_russian_1ru0',
    '1RU0',
    'Section 1: High-frequency language / Common verbs',
    'section-1:high-frequency-language:common-verbs:list'
  from upserted_set
  on conflict (source_key, import_key)
  where source_key is not null and import_key is not null
  do update
  set
    title = excluded.title,
    description = excluded.description,
    theme_key = excluded.theme_key,
    topic_key = excluded.topic_key,
    category_key = excluded.category_key,
    tier = excluded.tier,
    list_mode = excluded.list_mode,
    default_display_variant = excluded.default_display_variant,
    is_published = excluded.is_published,
    sort_order = excluded.sort_order,
    source_version = excluded.source_version,
    source_section_ref = excluded.source_section_ref,
    updated_at = now()
  returning id, vocabulary_set_id
),
raw_items (
  position,
  english,
  russian,
  notes,
  aspect_hint
) as (
  values
    (1, $$to accept$$, $$принимать/принять$$, null, null),
    (2, $$to argue$$, $$спорить/поспорить$$, null, null),
    (3, $$to ask$$, $$спрашивать/спросить$$, null, null),
    (4, $$to ask (for something)$$, $$просить/попросить (что-нибудь)$$, null, null),
    (5, $$to ask a question$$, $$задавать/задать вопрос$$, null, null),
    (6, $$to bathe$$, $$купаться/ис-$$, $$Spec gives perfective prefix shorthand.$$, null),
    (7, $$to be born$$, $$рождаться/родиться$$, null, null),
    (8, $$to begin, start$$, $$начинать(ся)/начать(ся)$$, null, null),
    (9, $$to be ill; to hurt$$, $$болеть/за-$$, $$Spec gives perfective prefix shorthand.$$, null),
    (10, $$to be interested in$$, $$интересоваться/за-$$, $$Spec gives perfective prefix shorthand.$$, null),
    (11, $$to be missing$$, $$отсутствовать$$, null, 'unknown'),
    (12, $$to be situated$$, $$находиться$$, null, 'unknown'),
    (13, $$to become$$, $$становиться/стать$$, null, null),
    (14, $$to believe$$, $$верить/по-$$, $$Spec gives perfective prefix shorthand.$$, null),
    (15, $$to buy$$, $$покупать/купить$$, null, null),
    (16, $$to carry$$, $$носить/нести//понести$$, null, null),
    (17, $$to chat$$, $$разговаривать$$, null, 'unknown'),
    (18, $$to check$$, $$проверять/проверить$$, null, null),
    (19, $$to change$$, $$меняться$$, $$Imperfective only in source.$$, 'imperfective'),
    (20, $$to choose$$, $$выбирать/выбрать$$, null, null),
    (21, $$to clean$$, $$чистить/по-$$, $$Spec gives perfective prefix shorthand.$$, null),
    (22, $$to clear away$$, $$убирать/убрать$$, null, null),
    (23, $$to click (ICT)$$, $$нажимать/нажать$$, null, null),
    (24, $$to close$$, $$закрывать/закрыть$$, null, null),
    (25, $$to collect$$, $$собирать/собрать$$, null, null),
    (26, $$to come$$, $$приходить/прийти$$, null, null),
    (27, $$to consider$$, $$считать$$, null, 'unknown'),
    (28, $$to contact$$, $$связываться/связаться$$, null, null),
    (29, $$to continue$$, $$продолжаться$$, null, 'unknown'),
    (30, $$to continue/carry on$$, $$продолжать/продолжить$$, null, null),
    (31, $$to convince$$, $$убеждать/убедить$$, null, null),
    (32, $$to cook$$, $$готовить/при-$$, $$Spec gives perfective prefix shorthand.$$, null),
    (33, $$to cope/manage/get by$$, $$справляться/справиться$$, null, null),
    (34, $$to copy$$, $$копировать/с-$$, $$Spec gives perfective prefix shorthand.$$, null),
    (35, $$to cost$$, $$стоить$$, null, 'unknown'),
    (36, $$to cross, go across$$, $$переходить/перейти$$, null, null),
    (37, $$to cry$$, $$плакать/за-$$, $$Spec gives perfective prefix shorthand.$$, null),
    (38, $$to decide$$, $$решать/решить$$, null, null),
    (39, $$to depart/leave$$, $$уезжать/уехать$$, null, null),
    (40, $$to depart/leave$$, $$уходить/уйти$$, null, null),
    (41, $$to describe$$, $$описывать/описать$$, null, null),
    (42, $$to die$$, $$умирать/умереть$$, null, null),
    (43, $$to discuss$$, $$обсуждать/обсудить$$, null, null),
    (44, $$to do$$, $$делать/сделать$$, $$Corrected obvious OCR from source text.$$, null),
    (45, $$to draw$$, $$рисовать/на-$$, $$Spec gives perfective prefix shorthand.$$, null),
    (46, $$to drink$$, $$пить/вы-$$, $$Spec gives perfective prefix shorthand.$$, null),
    (47, $$to drive$$, $$водить/вести//повести машину$$, null, null),
    (48, $$to earn$$, $$зарабатывать/заработать$$, null, null),
    (49, $$to eat$$, $$есть/съ-$$, $$Spec gives perfective prefix shorthand.$$, null),
    (50, $$to eat$$, $$кушать/по-$$, $$Spec gives perfective prefix shorthand.$$, null),
    (51, $$to end, finish$$, $$кончать(ся)/кончить(ся); заканчивать(ся)/закончить(ся)$$, $$Line break corrected from source text.$$, null),
    (52, $$to enjoy$$, $$увлекаться$$, null, 'unknown'),
    (53, $$to enjoy oneself$$, $$хорошо проводить/провести время$$, null, null),
    (54, $$to enter/go in$$, $$входить/войти$$, null, null),
    (55, $$to exist$$, $$существовать$$, null, 'unknown'),
    (56, $$to explain$$, $$объяснять/объяснить$$, null, null),
    (57, $$to fail (exam)$$, $$проваливать/провалить экзамен$$, null, null),
    (58, $$to fall$$, $$падать/упасть$$, null, null),
    (59, $$to fall asleep$$, $$засыпать/заснуть$$, null, null),
    (60, $$to feed, nourish$$, $$кормить/по-$$, $$Spec gives perfective prefix shorthand.$$, null),
    (61, $$to fill/fill in$$, $$заполнять/заполнить$$, null, null),
    (62, $$to find$$, $$находить/найти$$, null, null),
    (63, $$to find out$$, $$узнавать/узнать$$, null, null),
    (64, $$to finish$$, $$заканчивать(ся)/закончить(ся)$$, null, null),
    (65, $$to fly$$, $$летать/лететь//полететь$$, null, null),
    (66, $$to follow$$, $$следовать/по-$$, $$Spec gives perfective prefix shorthand.$$, null),
    (67, $$to forget$$, $$забывать/забыть$$, null, null),
    (68, $$to forgive$$, $$прощать/простить$$, null, null),
    (69, $$to get angry$$, $$сердиться/рассердиться$$, null, null),
    (70, $$to get dressed$$, $$одеваться/одеться$$, null, null),
    (71, $$to get into (bus, car, train)$$, $$садиться/сесть в (автобус, машину, поезд)$$, null, null),
    (72, $$to get out of (bus, car, train)$$, $$выходить/выйти из (автобуса, машины, поезда)$$, null, null),
    (73, $$to get undressed$$, $$раздеваться/раздеться$$, null, null),
    (74, $$to get up$$, $$вставать/встать$$, null, null),
    (75, $$to give$$, $$давать/дать$$, null, null),
    (76, $$to give (a gift/present)$$, $$дарить/по-$$, $$Spec gives perfective prefix shorthand.$$, null),
    (77, $$to give back$$, $$отдавать/отдать$$, null, null),
    (78, $$to go$$, $$ходить/идти//пойти$$, null, null),
    (79, $$to go (and come back); make a round trip$$, $$сходить$$, $$Perfective only in source.$$, 'perfective'),
    (80, $$to go (in a car)$$, $$ездить/ехать//поехать (в машине)$$, null, null),
    (81, $$to go down$$, $$спускаться/спуститься$$, null, null),
    (82, $$to go for a walk$$, $$гулять/по-$$, $$Spec gives perfective prefix shorthand.$$, null),
    (83, $$to go out$$, $$выходить/выйти$$, null, null),
    (84, $$to go to bed$$, $$ложиться/лечь спать$$, null, null),
    (85, $$to go up$$, $$подниматься/подняться$$, null, null),
    (86, $$to grow$$, $$расти/вы-$$, $$Spec gives perfective prefix shorthand.$$, null),
    (87, $$to happen$$, $$случаться/случиться$$, null, null),
    (88, $$to harm/damage$$, $$вредить/по-$$, $$Spec gives perfective prefix shorthand.$$, null),
    (89, $$to hate$$, $$ненавидеть/воз-$$, $$Spec gives perfective prefix shorthand.$$, null),
    (90, $$to have breakfast$$, $$завтракать/по-$$, $$Spec gives perfective prefix shorthand.$$, null),
    (91, $$to have lunch$$, $$обедать/по-$$, $$Spec gives perfective prefix shorthand.$$, null),
    (92, $$to have dinner/supper$$, $$ужинать/по-$$, $$Spec gives perfective prefix shorthand.$$, null),
    (93, $$to hear$$, $$слышать/у-$$, $$Spec gives perfective prefix shorthand.$$, null),
    (94, $$to help$$, $$помогать/помочь$$, null, null),
    (95, $$to hire$$, $$брать/взять напрокат$$, null, null),
    (96, $$to hit$$, $$ударять/ударить$$, null, null),
    (97, $$to hold$$, $$держать/по-$$, $$Spec gives perfective prefix shorthand.$$, null),
    (98, $$to hope$$, $$надеяться$$, null, 'unknown'),
    (99, $$to hurry$$, $$спешить/по-$$, $$Spec gives perfective prefix shorthand.$$, null),
    (100, $$to improve$$, $$улучшать/улучшить$$, null, null),
    (101, $$to inform$$, $$сообщать/сообщить$$, null, null),
    (102, $$to intend$$, $$намереваться$$, null, 'unknown'),
    (103, $$to intend$$, $$собираться$$, null, 'unknown'),
    (104, $$to interest$$, $$интересовать/за-$$, $$Spec gives perfective prefix shorthand.$$, null),
    (105, $$to introduce (a person)$$, $$представлять/представить$$, null, null),
    (106, $$to invite$$, $$приглашать/пригласить$$, null, null),
    (107, $$to iron$$, $$гладить/по-$$, $$Spec gives perfective prefix shorthand.$$, null),
    (108, $$to jump$$, $$прыгать/прыгнуть$$, null, null),
    (109, $$to justify$$, $$оправдывать/оправдать$$, null, null),
    (110, $$to knock$$, $$стучать/стукнуть$$, $$Corrected obvious OCR from source text.$$, null),
    (111, $$to knock over$$, $$сбивать/сбить (с ног)$$, null, null),
    (112, $$to know$$, $$знать$$, null, 'unknown'),
    (113, $$to know how to$$, $$уметь$$, null, 'unknown'),
    (114, $$to land$$, $$приземляться/приземлиться$$, null, null),
    (115, $$to last$$, $$длиться$$, null, 'unknown'),
    (116, $$to laugh$$, $$смеяться/за-$$, $$Spec gives perfective prefix shorthand.$$, null),
    (117, $$to lead$$, $$водить/вести//повести$$, null, null),
    (118, $$to learn$$, $$учиться$$, null, 'unknown'),
    (119, $$to leave (behind)$$, $$оставлять/оставить$$, null, null),
    (120, $$to leave; to depart$$, $$уезжать/уехать$$, null, null),
    (121, $$to leave; to depart$$, $$уходить/уйти$$, null, null),
    (122, $$to lie$$, $$лежать/по-$$, $$Spec gives perfective prefix shorthand.$$, null),
    (123, $$to lie down$$, $$ложиться/лечь$$, null, null),
    (124, $$to light, turn/switch on$$, $$включать/включить$$, null, null),
    (125, $$to like$$, $$нравиться/по-$$, $$Spec gives perfective prefix shorthand.$$, null),
    (126, $$to listen$$, $$слушать/по-$$, $$Spec gives perfective prefix shorthand.$$, null),
    (127, $$to live$$, $$жить$$, null, 'unknown'),
    (128, $$to look after/mind (child, dog)$$, $$присматривать/присмотреть$$, null, null),
    (129, $$to look for$$, $$искать/по-$$, $$Spec gives perfective prefix shorthand.$$, null),
    (130, $$to lose$$, $$терять/по-$$, $$Spec gives perfective prefix shorthand.$$, null),
    (131, $$to lose$$, $$проигрывать/проиграть$$, null, null),
    (132, $$to love$$, $$любить/по-$$, $$Spec gives perfective prefix shorthand.$$, null),
    (133, $$to manage (business)$$, $$руководить$$, null, 'unknown'),
    (134, $$to manage, to cope$$, $$справляться/справиться$$, null, null),
    (135, $$to mean to (do)$$, $$собираться/собраться$$, null, null),
    (136, $$to mean/to signify$$, $$значить$$, null, 'unknown'),
    (137, $$to meet$$, $$встречать(ся)/встретить(ся)$$, null, null),
    (138, $$to miss (appointment, etc)$$, $$пропускать/пропустить$$, null, null),
    (139, $$to miss (train, bus etc)$$, $$опаздывать/опоздать (на поезд, автобус)$$, null, null),
    (140, $$to notice$$, $$замечать/заметить$$, null, null),
    (141, $$to offer$$, $$предлагать/предложить$$, null, null),
    (142, $$to open$$, $$открывать/открыть$$, null, null),
    (143, $$to order$$, $$заказывать/заказать$$, null, null),
    (144, $$to organise$$, $$организовать$$, null, 'unknown'),
    (145, $$to park$$, $$парковаться/при-$$, $$Spec gives perfective prefix shorthand.$$, null),
    (146, $$to park$$, $$ставить/по- (машину)$$, $$Spec gives perfective prefix shorthand.$$, null),
    (147, $$to pay$$, $$платить/за-$$, $$Spec gives perfective prefix shorthand.$$, null),
    (148, $$to phone$$, $$звонить/по-$$, $$Spec gives perfective prefix shorthand.$$, null),
    (149, $$to play$$, $$играть/по-$$, $$Spec gives perfective prefix shorthand.$$, null),
    (150, $$to pop in/go in$$, $$заходить/зайти$$, null, null),
    (151, $$to possess$$, $$иметь$$, null, 'unknown'),
    (152, $$to prefer$$, $$предпочитать/предпочесть$$, $$Corrected obvious OCR from source text.$$, null),
    (153, $$to prepare$$, $$готовить(ся)/подготовить(ся)$$, null, null),
    (154, $$to present$$, $$представлять/представить$$, null, null),
    (155, $$to prevent$$, $$предотвращать/предотвратить$$, null, null),
    (156, $$to produce$$, $$производить/произвести$$, null, null),
    (157, $$to put$$, $$класть/положить$$, null, null),
    (158, $$to put back$$, $$класть/положить на место$$, null, null),
    (159, $$to put on$$, $$надевать/надеть$$, null, null),
    (160, $$to read$$, $$читать/про-$$, $$Spec gives perfective prefix shorthand.$$, null),
    (161, $$to receive$$, $$получать/получить$$, null, null),
    (162, $$to recommend$$, $$рекомендовать$$, null, 'unknown'),
    (163, $$to refund$$, $$возмещать/возместить$$, null, null),
    (164, $$to regret, be sorry$$, $$жалеть/сожалеть$$, null, null),
    (165, $$to remain$$, $$оставаться/остаться$$, null, null),
    (166, $$to remember$$, $$помнить/вс-$$, $$Spec gives perfective prefix shorthand.$$, null),
    (167, $$to reminisce, recall$$, $$вспоминать$$, null, 'unknown'),
    (168, $$to repair$$, $$чинить/по-$$, $$Spec gives perfective prefix shorthand.$$, null),
    (169, $$to repeat$$, $$повторять/повторить$$, null, null),
    (170, $$to replace$$, $$заменять/заменить$$, null, null),
    (171, $$to reply$$, $$отвечать/ответить$$, null, null),
    (172, $$to research$$, $$исследовать/от-$$, $$Spec gives perfective prefix shorthand.$$, null),
    (173, $$to reserve$$, $$заказывать/заказать$$, null, null),
    (174, $$to rest$$, $$отдыхать/отдохнуть$$, null, null),
    (175, $$to return$$, $$возвращать/вернуть$$, null, null),
    (176, $$to return; to go back$$, $$возвращаться/вернуться$$, null, null),
    (177, $$to ride a horse$$, $$кататься на лошади$$, null, 'unknown'),
    (178, $$to ring (a bell)$$, $$звонить/по-$$, $$Spec gives perfective prefix shorthand.$$, null),
    (179, $$to run$$, $$бегать/бежать//побежать$$, null, null),
    (180, $$to save$$, $$спасать/спасти$$, null, null),
    (181, $$to say$$, $$говорить/сказать$$, null, null),
    (182, $$to see$$, $$видеть/у-$$, $$Spec gives perfective prefix shorthand.$$, null),
    (183, $$to seem$$, $$казаться/по-$$, $$Spec gives perfective prefix shorthand.$$, null),
    (184, $$to sell$$, $$продавать/продать$$, null, null),
    (185, $$to send$$, $$посылать/послать$$, null, null),
    (186, $$to serve$$, $$служить$$, null, 'unknown'),
    (187, $$to show$$, $$показывать/показать$$, null, null),
    (188, $$to sign$$, $$подписывать/подписать$$, null, null),
    (189, $$to sing$$, $$петь/с-$$, $$Spec gives perfective prefix shorthand.$$, null),
    (190, $$to sit$$, $$сидеть/по-$$, $$Spec gives perfective prefix shorthand.$$, null),
    (191, $$to sit down$$, $$садиться/сесть$$, null, null),
    (192, $$to sit (someone); to plant$$, $$садить/по-$$, $$Spec gives perfective prefix shorthand.$$, null),
    (193, $$to skate$$, $$кататься на коньках$$, $$Corrected obvious OCR from source text.$$, 'unknown'),
    (194, $$to ski$$, $$кататься на лыжах$$, null, 'unknown'),
    (195, $$to sleep$$, $$спать/по-$$, $$Spec gives perfective prefix shorthand.$$, null),
    (196, $$to smile$$, $$улыбаться/улыбнуться$$, null, null),
    (197, $$to smoke$$, $$курить/вы-$$, $$Spec gives perfective prefix shorthand.$$, null),
    (198, $$to solve (a problem)$$, $$решать/решить (проблему)$$, null, null),
    (199, $$to speak$$, $$говорить/сказать$$, null, null),
    (200, $$to spend (money)$$, $$тратить/по- (деньги)$$, $$Spec gives perfective prefix shorthand.$$, null),
    (201, $$to spend (time)$$, $$проводить/провести (время)$$, null, null),
    (202, $$to stand$$, $$стоять/по-$$, $$Spec gives perfective prefix shorthand.$$, null),
    (203, $$to stand up$$, $$вставать/встать$$, null, null),
    (204, $$to steal$$, $$красть/у-$$, $$Spec gives perfective prefix shorthand.$$, null),
    (205, $$to stop$$, $$останавливать(ся)/остановить(ся)$$, null, null),
    (206, $$to stroll, go for a walk$$, $$гулять/по-$$, $$Spec gives perfective prefix shorthand.$$, null),
    (207, $$to study (a subject)$$, $$изучать$$, null, 'unknown'),
    (208, $$to study (be a student)$$, $$учиться$$, null, 'unknown'),
    (209, $$to sunbathe$$, $$загорать$$, null, 'unknown'),
    (210, $$to swim$$, $$плавать/плыть//поплыть$$, null, null),
    (211, $$to switch off$$, $$выключать/выключить$$, null, null),
    (212, $$to take$$, $$брать/взять$$, null, null),
    (213, $$to take off (clothes etc)$$, $$снимать/снять$$, null, null),
    (214, $$to take off (plane)$$, $$взлетать/взлететь$$, null, null),
    (215, $$to take one's coat off$$, $$раздеваться/раздеться$$, null, null),
    (216, $$to taste$$, $$пробовать/по-$$, $$Spec gives perfective prefix shorthand.$$, null),
    (217, $$to tell/recount$$, $$рассказывать/рассказать$$, null, null),
    (218, $$to tell/to say$$, $$говорить/сказать$$, null, null),
    (219, $$to thank$$, $$благодарить/по-$$, $$Spec gives perfective prefix shorthand.$$, null),
    (220, $$to think (about)$$, $$думать/по- (о чём-либо)$$, $$Spec gives perfective prefix shorthand.$$, null),
    (221, $$to throw$$, $$бросать/бросить$$, null, null),
    (222, $$to touch$$, $$трогать/тронуть$$, null, null),
    (223, $$to travel$$, $$путешествовать$$, null, 'unknown'),
    (224, $$to try$$, $$пробовать/по-$$, $$Spec gives perfective prefix shorthand.$$, null),
    (225, $$to understand$$, $$понимать/понять$$, null, null),
    (226, $$to use$$, $$использовать$$, null, 'unknown'),
    (227, $$to use$$, $$пользоваться/ис-$$, $$Spec gives perfective prefix shorthand.$$, null),
    (228, $$to vacuum$$, $$пылесосить/про-$$, $$Spec gives perfective prefix shorthand.$$, null),
    (229, $$to visit (person)$$, $$навещать/навестить$$, null, null),
    (230, $$to visit (place)$$, $$посещать/посетить$$, null, null),
    (231, $$to wait for; to expect$$, $$ждать/подождать$$, null, null),
    (232, $$to wake up$$, $$просыпаться/проснуться$$, null, null),
    (233, $$to walk$$, $$ходить/идти//пойти$$, null, null),
    (234, $$to want$$, $$хотеть/за-$$, $$Spec gives perfective prefix shorthand.$$, null),
    (235, $$to warn$$, $$предупреждать/предупредить$$, null, null),
    (236, $$to wash$$, $$мыть/вы-$$, $$Spec gives perfective prefix shorthand.$$, null),
    (237, $$to wash (oneself)$$, $$умываться/умыться$$, null, null),
    (238, $$to wash, launder$$, $$стирать/по-$$, $$Spec gives perfective prefix shorthand.$$, null),
    (239, $$to watch$$, $$смотреть/по-$$, $$Spec gives perfective prefix shorthand.$$, null),
    (240, $$to wear$$, $$носить/нести//понести$$, null, null),
    (241, $$to weigh (have weight)$$, $$весить$$, null, 'unknown'),
    (242, $$to weigh (sth.)$$, $$взвешивать/взвесить$$, null, null),
    (243, $$to win$$, $$выигрывать/выиграть$$, null, null),
    (244, $$to wish$$, $$желать/по-$$, $$Spec gives perfective prefix shorthand.$$, null),
    (245, $$to work$$, $$работать/по-$$, $$Spec gives perfective prefix shorthand.$$, null),
    (246, $$to write$$, $$писать/на-$$, $$Spec gives perfective prefix shorthand.$$, null)
),
prepared_items as (
  select
    raw_items.position,
    raw_items.english,
    raw_items.russian,
    raw_items.notes,
    case
      when raw_items.aspect_hint is not null then raw_items.aspect_hint
      when raw_items.russian like '%/%' then 'both'
      else 'unknown'
    end as aspect,
    case
      when raw_items.russian ~ '\s' or raw_items.russian like '%(%' or raw_items.russian like '%;%' then 'phrase'
      else 'word'
    end as item_type,
    (
      'section-1:high-frequency-language:common-verbs:item-' ||
      lpad(raw_items.position::text, 3, '0')
    ) as import_key,
    regexp_replace(
      lower(
        translate(
          raw_items.english,
          '()'',.;/',
          '       '
        )
      ),
      '[^a-z0-9]+',
      '-',
      'g'
    ) as canonical_key
  from raw_items
),
upserted_items as (
  insert into public.vocabulary_items (
    vocabulary_set_id,
    canonical_key,
    russian,
    english,
    item_type,
    source_type,
    priority,
    part_of_speech,
    gender,
    productive_receptive,
    tier,
    theme_key,
    topic_key,
    category_key,
    aspect,
    is_reflexive,
    source_key,
    source_version,
    source_section_ref,
    import_key,
    position,
    notes
  )
  select
    upserted_list.vocabulary_set_id,
    trim(both '-' from prepared_items.canonical_key),
    prepared_items.russian,
    prepared_items.english,
    prepared_items.item_type,
    'spec_required',
    'core',
    'verb',
    'not_applicable',
    'unknown',
    'both',
    'high_frequency_language',
    'common_verbs',
    'common_verbs',
    prepared_items.aspect,
    prepared_items.russian like '%ся%' or prepared_items.russian like '%сь%',
    'pearson_edexcel_gcse_russian_1ru0',
    '1RU0',
    'Section 1: High-frequency language / Common verbs',
    prepared_items.import_key,
    prepared_items.position,
    prepared_items.notes
  from prepared_items
  cross join upserted_list
  on conflict (source_key, import_key)
  where source_key is not null and import_key is not null
  do update
  set
    vocabulary_set_id = excluded.vocabulary_set_id,
    canonical_key = excluded.canonical_key,
    russian = excluded.russian,
    english = excluded.english,
    item_type = excluded.item_type,
    source_type = excluded.source_type,
    priority = excluded.priority,
    part_of_speech = excluded.part_of_speech,
    gender = excluded.gender,
    productive_receptive = excluded.productive_receptive,
    tier = excluded.tier,
    theme_key = excluded.theme_key,
    topic_key = excluded.topic_key,
    category_key = excluded.category_key,
    aspect = excluded.aspect,
    is_reflexive = excluded.is_reflexive,
    source_version = excluded.source_version,
    source_section_ref = excluded.source_section_ref,
    position = excluded.position,
    notes = excluded.notes,
    updated_at = now()
  returning id, import_key, position
)
insert into public.vocabulary_list_items (
  vocabulary_list_id,
  vocabulary_item_id,
  position,
  productive_receptive_override,
  tier_override,
  source_section_ref,
  import_key
)
select
  upserted_list.id,
  upserted_items.id,
  upserted_items.position,
  null,
  'both',
  'Section 1: High-frequency language / Common verbs',
  upserted_items.import_key
from upserted_items
cross join upserted_list
on conflict (vocabulary_list_id, import_key)
where import_key is not null
do update
set
  vocabulary_item_id = excluded.vocabulary_item_id,
  position = excluded.position,
  productive_receptive_override = excluded.productive_receptive_override,
  tier_override = excluded.tier_override,
  source_section_ref = excluded.source_section_ref;

commit;
